### ISSUE TITLE
[BUG] Error: Call to undefined function () in /opt/datadog-php/dd-trace-sources/bridge/functions.php:138

### ISSUE THREAD

**Issue by ThomasVdBerge** [DataDog/dd-trace-php#865] opened 2020-05-01 17:51 UTC
**Describe the bug**
When running this plugin on PHP 7.4.5 we often get the following error. Out setup runs on AWS Fargate:

```
PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function () in /opt/datadog-php/dd-trace-sources/bridge/functions.php:138
thrown in /opt/datadog-php/dd-trace-sources/bridge/functions.php on line 138
#0 /app/vendor/composer/autoload_real.php(25): ComposerAutoloaderInit26ebf97ffdb7575dcfd32f97a9330f1b::dd_trace_callback(Array, true, true)
#1 /app/vendor/autoload.php(7): ComposerAutoloaderInit26ebf97ffdb7575dcfd32f97a9330f1b::getLoader()
#2 /app/public_html/index.php(2): require('/app/vendor/aut...')
```

This causes the docker container to crash and restart. 

We are not seeing this behavior on 7.4.4.

**PHP Info**
- Output of `php -v`

> PHP 7.4.5 (cli) (built: Apr 24 2020 17:44:59) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies
>     with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies

- Output of `php -m`

> [PHP Modules]
> apcu
> bcmath
> bz2
> calendar
> Core
> ctype
> curl
> date
> ddtrace
> dom
> exif
> fileinfo
> filter
> ftp
> gd
> geoip
> gmp
> hash
> iconv
> intl
> json
> libxml
> mbstring
> memcached
> mysqlnd
> openssl
> pcntl
> pcre
> PDO
> pdo_mysql
> pdo_sqlite
> Phar
> posix
> readline
> Reflection
> session
> SimpleXML
> soap
> sodium
> SPL
> sqlite3
> standard
> sysvmsg
> sysvsem
> sysvshm
> tokenizer
> xml
> xmlreader
> xmlwriter
> Zend OPcache
> zip
> zlib
> 
> [Zend Modules]
> Zend OPcache

**OS Info**
- Output of `cat /etc/os-release | grep -E "(NAME)|(VERSION)"`

> NAME="Alpine Linux"
> VERSION_ID=3.11.6
> PRETTY_NAME="Alpine Linux v3.11"

**Output of dd-doctor**

> 
> DataDog trace extension verification
> 
> - PHP version and SAPI                               [7.4.5 - fpm-fcgi]
> - ddtrace extension installed                        [OK]
> - ddtrace version (installed)                        [0.41.1]
> - ddtrace version (const)                            [0.41.1]
> - ddtrace version (userland)                         [0.41.1]
> - ddtrace versions in sync                           [OK]
> - dd_trace() function available                      [OK]
> - dd_trace_env_config() function available           [OK]
> - ddtrace.request_init_hook set                      [OK]
> - ddtrace.request_init_hook reachable                [OK]
> - ddtrace.request_init_hook has run                  [OK]
> - 'open_basedir' allows access to '/proc/self/'      [OK]
> - IntegrationsLoader exists                          [OK]
> - Integrations not loaded yet                        [OK]
> - Registering an autoloader...
> - Integrations loaded                                [OK]
> - DDTrace\Tracer class exists                        [OK]
> - Background sender is enabled?                      [NO]
>   > You can enable the background sender via
>     DD_TRACE_BETA_SEND_TRACES_VIA_THREAD=true
> - Configured Agent host                              [localhost]
> - Configured Agent port                              [8126]
> - Agent can receive traces                           [FAIL]
> Curl verbose output: 
> 
> *   Trying 127.0.0.1:8126...
> * TCP_NODELAY set
> * connect to 127.0.0.1 port 8126 failed: Connection refused
> *   Trying ::1:8126...
> * TCP_NODELAY set
> * Immediate connect fail for ::1: Address not available
> *   Trying ::1:8126...
> * TCP_NODELAY set
> * Immediate connect fail for ::1: Address not available
> * Failed to connect to localhost port 8126: Connection refused
> * Closing connection 0
>

**Comment by morrisonlevi** [comment] 2020-05-01 18:39
I'm investigating now.

Aside from the issue you reported, it looks like in dd-doctor it couldn't contact the agent. How do you set your agent hostname?

**Comment by morrisonlevi** [comment] 2020-05-01 22:48
I haven't been able to reproduce this yet.

If you are itching to try something new then there is a possibility that the [latest Alpine master build](https://148937-119990860-gh.circle-artifacts.com/0/datadog-php-tracer_1.0.0-nightly_noarch.apk) will fix your issue. I will resume investigation next week. Have a good weekend!

**Comment by ThomasVdBerge** [comment] 2020-05-02 07:41
> I'm investigating now.
> 
> Aside from the issue you reported, it looks like in dd-doctor it couldn't contact the agent. How do you set your agent hostname?

We use the ECS task-definition to set the correct vars. These were indeed not present in my local testing

**Comment by morrisonlevi** [comment] 2020-05-05 19:07
Thomas, if you set `DD_TRACE_NO_AUTOLOADER=1` in an environment variable or SAPI config, does the issue go away?

**Comment by morrisonlevi** [comment] 2020-05-06 16:27
@ThomasVdBerge, I'm checking in again; if you set `DD_TRACE_NO_AUTOLOADER=1` does your issue go away? I expect that it will as it takes a different code-path that doesn't use composer based autoloading at all.

**Comment by morrisonlevi** [comment] 2020-05-08 13:00
@ThomasVdBerge I haven't been able to reproduce this yet. I'm wondering if it's specific to certain opcache settings; can you share those? At the same time, you should try setting `DD_TRACE_NO_AUTOLOADER` to 1 in your environment; I'm pretty sure it will avoid the problem.

**Comment by ThomasVdBerge** [comment] 2020-05-11 12:24
@morrisonlevi We've tried that build, unfortunately it still gives us a couple of errors.

With that var set to the following in our ECS TaskDefinition

`        {
          "name": "DD_TRACE_NO_AUTOLOADER",
          "value": "1"
        },
`
We get the following error:

> [error] 6#6: *486 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Access to undeclared static property: ::$ in /opt/datadog-php/dd-trace-sources/bridge/dd_optional_deps_autoloader.php:46

This is also on PHP 7.4.4 now (The first error aswell, it just did not appear right away). 

We indeed have opcache enabled

> 
> Opcode Caching | Up and Running
> -- | --
> Optimization | Enabled
> SHM Cache | Enabled
> File Cache | Disabled
> Startup | OK
> Shared memory model | mmap
> Cache hits | 0
> Cache misses | 1
> Used memory | 17556312
> Free memory | 519314600
> Wasted memory | 0
> Interned Strings Used memory | 382304
> Interned Strings Free memory | 12200160
> Cached scripts | 0
> Cached keys | 0
> Max keys | 16229
> OOM restarts | 0
> Hash keys restarts | 0
> Manual restarts | 3
> 
> 

> 
> Directive | Local Value | Master Value
> -- | -- | --
> opcache.blacklist_filename | no value | no value
> opcache.consistency_checks | 0 | 0
> opcache.dups_fix | Off | Off
> opcache.enable | On | On
> opcache.enable_cli | Off | Off
> opcache.enable_file_override | Off | Off
> opcache.error_log | no value | no value
> opcache.file_cache | no value | no value
> opcache.file_cache_consistency_checks | 1 | 1
> opcache.file_cache_only | 0 | 0
> opcache.file_update_protection | 2 | 2
> opcache.force_restart_timeout | 180 | 180
> opcache.huge_code_pages | Off | Off
> opcache.interned_strings_buffer | 16 | 16
> opcache.lockfile_path | /tmp | /tmp
> opcache.log_verbosity_level | 1 | 1
> opcache.max_accelerated_files | 8000 | 8000
> opcache.max_file_size | 0 | 0
> opcache.max_wasted_percentage | 5 | 5
> opcache.memory_consumption | 512 | 512
> opcache.opt_debug_level | 0 | 0
> opcache.optimization_level | 0x7FFEBFFF | 0x7FFEBFFF
> opcache.preferred_memory_model | no value | no value
> opcache.preload | no value | no value
> opcache.preload_user | no value | no value
> opcache.protect_memory | 0 | 0
> opcache.restrict_api | no value | no value
> opcache.revalidate_freq | 2 | 2
> opcache.revalidate_path | Off | Off
> opcache.save_comments | 1 | 1
> opcache.use_cwd | On | On
> opcache.validate_permission | Off | Off
> opcache.validate_root | Off | Off
> opcache.validate_timestamps | Off | Off
> 
>

**Comment by morrisonlevi** [comment] 2020-05-11 16:24
Are you updating PHP files without a server restart, by chance? Also, what webserver do you have in front of the php-fpm SAPI?

**Comment by morrisonlevi** [comment] 2020-05-15 14:41
@ThomasVdBerge Still I have been unable to reproduce this. I have a few questions:

- Do you have a container or any specific tips that you could share with me to reproduce this issue?
- What does your entrypoint for the app looks like; is it doing much if any work before registering an autoloader?
- The opcache settings you provided look entirely default; does that sound right to you?

**Comment by morrisonlevi** [comment] 2020-05-18 22:28
Since we have been unable to reproduce this and haven't heard anything in a week, I plan to close this issue soon. I recommend upgrading the tracer to the latest version (0.45.1, released today) and letting us know if you still have the issue; we have overhauled quite a bit of the tracer since 0.41.1. If you still have the issue, please try to include more information on how to reproduce it.

**Comment by labbati** [comment] 2020-05-20 12:24
Hi @ThomasVdBerge! I am closing this issue as stale. We tried many different path to recreate the issue but we were not able, so it must be something related to our tracer within your specific environment. Please in case you still see the problem once you upgrade to 0.45.2 as recommended by @morrisonlevi feel free to open a support ticket as we will have to access 
more info about your setup which might not be sharable publicly.
Thanks for taking the time to report it and I am sorry you had to got through it

**Comment by ThomasVdBerge** [comment] 2020-05-27 12:19
Upgrading to 0.45.2 seems to have solved this issue!

**Comment by labbati** [comment] 2020-05-27 12:22
Thanks for confirming

**Comment by rbait** [comment] 2020-06-01 12:54
Hi all, I'm a colleague of Thomas,

Unfortunately the issue isn't fixed yet with .2, we cheered too soon :) 

The problem seems to be $callable_name is empty after the is_callable call. We also get a warning about that in the logs: 
`PHP Warning:  strpos(): Empty needle in /opt/datadog-php/dd-trace-sources/bridge/functions.php on line 114`

Maybe just adding an extra check before the strpos to see if $callable_name is empty would be enough to fix it?

I also noticed the functions.php file is gone from master completely, so that might already have fixed it?

**Comment by morrisonlevi** [comment] 2020-06-02 19:05
Sorry to hear that it isn't fixed. I'm in the process of releasing 0.46, which changes how bootstrapping works. I'm positive this specific issue will go away because we removed that entire code path, but I worry that it is actually some generic issue that is manifesting itself in this specific place. I'll let you know when 0.46 is officially out. You can upgrade and report back; if you still have issues we may need to set up a call to try to debug it on your machines, as we were never able to reproduce it before.

**Comment by morrisonlevi** [comment] 2020-06-02 22:24
Version [0.46.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.46.0) has been released. Again, please let us know if the issue manifests somewhere else.

**Comment by labbati** [comment] 2020-06-03 10:17
Hi @rbait, sorry to hear that too. Unfortunately we were not able to reproduce the issue, as Levi already had mentioned:

I only see to roads ahead to fix this. You can try 0.46.0 but I'd prefer you not to run 'experiments' on your environment. But we the current level of info we are not able to proceed in a different way. Alternatively, if you would be able to provide a Dockerfile and a minimal script that reproduces the issue we would super happy to work on this as a top priority issue.

**Comment by rbait** [comment] 2020-06-03 12:42
Thanks, we will run some tests on our staging environment with the new version. 

Providing a Dockerfile and minimal script won't help I'm afraid, as I suppose it is some super edge case. We use the same docker image on staging and production, both on AWS Fargate, so the envs should be pretty much identical, yet we're only seeing the issue on staging. So even for us it is weird and impossible to reproduce locally with the same image for example. It's also not happening on every request (even for the same page) on staging.

I'll keep you posted on the results

**Comment by rbait** [comment] 2020-06-03 14:00
Looking good so far, we've been testing for half an hour now, and before switching versions we were experiencing the error about 83 times during that timeframe, now 0 :)

We will keep it running on that version and will report back any issues, but I think it's safe to assume it's gone with refactoring/removing that part of the code 👍

**Comment by rbait** [comment] 2020-06-03 14:08
I'll also leave this here as maybe it helps you understanding what the issue was or where it originated. By going through the logs again I noticed 1 time the fatal error was slightly different:
```
NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function DDTrace\Bridge\dd_tracing_enabled() in /opt/datadog-php/dd-trace-sources/bridge/dd_init.php:12
Stack trace:
#0 /opt/datadog-php/dd-trace-sources/bridge/functions.php(126): require()
#1 /app/vendor/composer/ClassLoader.php(302): Composer\Autoload\ClassLoader::dd_trace_callback(Array, true, true)
#2 /app/vendor/composer/autoload_real.php(51): Composer\Autoload\ClassLoader->register(true)
#3 /app/vendor/autoload.php(7): ComposerAutoloaderInit8a9a6dbe77f2c4edcd7372480bcfc65b::getLoader()
#4 /app/public_html/index.php(2): require('/app/vendor/aut...')
#5 {main}
```

**Comment by labbati** [comment] 2020-06-04 16:00
Thanks for the additional info. We will dive deeper into this. Just to make it sure 100%. This error is before 0.46.0 (looking at old logs) and it does not exist on 0.46.0, works properly.

**Comment by rbait** [comment] 2020-06-04 16:10
Correct, 0.46 has been running fine for a day on our staging env, and is now also pushed to our production env without issues

**Comment by labbati** [comment] 2020-06-15 12:47
Hi @rbait, looking at your logs above nothing stands out from my side, other than something opcache. We are totally opened to investigate it together with you, but we'd need to setup a debug session on you machine as we are not able to recreate.

I am going ahead and closing this issue for now. Feel free to comment if you are available to do some form of debug session together. Also, you can open a support ticket in case we need to share confidential info.

**Closed by labbati** 2020-06-15 12:47 UTC
Labels: 🐛 bug
