### ISSUE TITLE
[Feature] Enable distributed tracing with dd_trace_method and dd_trace_function

### ISSUE THREAD

**Issue by Bibob7** [DataDog/dd-trace-php#915] opened 2020-06-09 06:46 UTC
**Is your feature request related to a problem? Please describe.**
In order to enable distributed tracing for example for grpc requests, in `dd_trace_method` or `dd_trace_function`, we need to be able to set and extract the trace id and parent id which are sent and received via headers.

**Describe the solution you'd like**
In `dd_trace_method` something like this should be possible:

When receiving a request:
```
$span->trace_id = $tracingHeaders[Propagator::DEFAULT_TRACE_ID_HEADER];
$span->parent_id = $tracingHeaders[Propagator::DEFAULT_PARENT_ID_HEADER];
```

When sending a request:
```
$tracingHeaders[Propagator::DEFAULT_TRACE_ID_HEADER] = $span->trace_id;
$tracingHeaders[Propagator::DEFAULT_PARENT_ID_HEADER] = $span->parent_id;
```

**Describe alternatives you've considered**
In general, I think it would be helpful, if the created internal span from `dd_trace_method` is configurable like in `dd_trace`

**Comment by labbati** [comment] 2020-09-09 10:42
@SammyK @morrisonlevi any thoughts on this?

**Comment by SammyK** [comment] 2020-09-09 23:25
@Bibob7 Thank you for the suggestion! We'll likely be tackling distributed tracing for internal spans created with the sandbox API as part of a refactor planned for the forth quarter. I've linked this issue in our internal system to track the refactor and we'll be following up with you when we make progress on it.

For what it's worth, if the span stack is empty at the beginning of the script, you can currently set the trace ID and the parent ID. So setting `DD_TRACE_GENERATE_ROOT_SPAN=0` to make sure the root span is not generated, then you can set the ID's with:

```php
\dd_trace_set_trace_id((string) $tracingHeaders[Propagator::DEFAULT_TRACE_ID_HEADER]);
\dd_trace_push_span_id((string) $tracingHeaders[Propagator::DEFAULT_PARENT_ID_HEADER]);
```

If the script keeps track of the `$traceId`, you can propagate it along with the active span ID with the following:

```php
$tracingHeaders[Propagator::DEFAULT_TRACE_ID_HEADER] = $traceId;
$tracingHeaders[Propagator::DEFAULT_PARENT_ID_HEADER] = \dd_trace_peek_span_id();
```

**Comment by Bibob7** [comment] 2021-04-16 06:34
> @Bibob7 Thank you for the suggestion! We'll likely be tackling distributed tracing for internal spans created with the sandbox API as part of a refactor planned for the forth quarter. I've linked this issue in our internal system to track the refactor and we'll be following up with you when we make progress on it.
> 
> For what it's worth, if the span stack is empty at the beginning of the script, you can currently set the trace ID and the parent ID. So setting `DD_TRACE_GENERATE_ROOT_SPAN=0` to make sure the root span is not generated, then you can set the ID's with:
> 
> ```
> \dd_trace_set_trace_id((string) $tracingHeaders[Propagator::DEFAULT_TRACE_ID_HEADER]);
> \dd_trace_push_span_id((string) $tracingHeaders[Propagator::DEFAULT_PARENT_ID_HEADER]);
> ```

When I do this before the request handle methods is called, I can't see traces anymore. Any idea what could be wrong?

**Comment by Bibob7** [comment] 2021-04-16 06:36
I also tried it like this, but I can't see any traces.

```php
\DDTrace\hook_method(
            'Spiral\GRPC\Server',
            'invoke',
            function ($app, $appClass, $args, $retval) use ($serviceName) {
                $context = $args[1];
                $traceId = $context->getValue(Propagator::DEFAULT_TRACE_ID_HEADER);
                if (is_array($traceId)) {
                    $traceId = $traceId[0];
                }
                $parentId = $context->getValue(Propagator::DEFAULT_PARENT_ID_HEADER);
                if (is_array($parentId)) {
                    $parentId = $parentId[0];
                }

                dd_trace_set_trace_id((string) $traceId);
                dd_trace_push_span_id((string) $parentId);

                \DDTrace\trace_method(
                    'Spiral\GRPC\ServiceWrapper',
                    'invoke',
                    function (SpanData $span, $args, $retval) use ($serviceName) {
                        $method = $args[0];

                        $span->name = GrpcIntegration::NAME . '.request.process';
                        $span->resource = $method;
                        $span->service = $serviceName;
                        $span->type = GrpcIntegration::NAME;
                    }
                );
            }
        );
```

**Comment by SammyK** [comment] 2021-04-20 16:01
@Bibob7 Until we are able to support gRPC natively, we might be able to set this up in a similar way to how we trace multiple invocations of a long-running CLI script.

This requires turning off root-span generation and enabling auto-flushing from internal spans:

```
DD_TRACE_AUTO_FLUSH_ENABLED=1
DD_TRACE_GENERATE_ROOT_SPAN=0
```

Here's a possible workaround that will enable distributed tracing from internal spans. I don't have much experience with gRPC, so I hope you're able to transpose it into something similar for gRPC:

```php
<?php

/* Get the HTTP request headers */
$headers = \DDTrace\Http\Request::getHeaders();
$is_distributed_trace = false;
/* If these headers are present, this is a distributed trace */
if (isset($headers['x-datadog-trace-id']) && isset($headers['x-datadog-parent-id'])) {
    /* Clear the span stack and reset the trace ID */
    \dd_trace_serialize_closed_spans();
    /* Set the trace ID to the distributed trace's ID */
    \dd_trace_set_trace_id($headers['x-datadog-trace-id']);
    /* Push the span ID that invoked this distributed request onto the span ID stack */
    \dd_trace_push_span_id($headers['x-datadog-parent-id']);
    $is_distributed_trace = true;
}

/* Trace the app entry point. This will be the root span. */
\DDTrace\trace_function('app_entry_point', function ($s) {
    $s->service = getenv('DD_SERVICE') ?: getenv('DD_SERVICE_NAME');
    $s->type = 'web';
});

function app_entry_point()
{
    /* Do work */
    usleep(500);
}

app_entry_point();

if ($is_distributed_trace) {
    /* Pop the last span ID off the stack that was pushed on from the
     * distributed request. This will invoke the tracer flush operation.
     */
    \dd_trace_pop_span_id();
}
```

**Comment by Bibob7** [comment] 2021-04-20 20:11
@SammyK:
Is it also possible to push and pop the spans in the hook method or something similar? This would be helpful, because then I don‘t need to implement it directly in the application code.

**Comment by SammyK** [comment] 2021-04-21 14:03
@Bibob7 While it is possible to push & pop span IDs from within a hooking closure, it can be a bit tricky to keep the span ID stack in sync with the span stack. But if the app has a bootstrapping/startup entry point to hook, we shouldn't need to push or pop from a hooking closure. Here's the above example rewritten without changing any of the application code:

```php
<?php

\DDTrace\hook_function('app_startup', function () {
    $headers = \DDTrace\Http\Request::getHeaders();
    if (isset($headers['x-datadog-trace-id']) && isset($headers['x-datadog-parent-id'])) {
        \dd_trace_serialize_closed_spans();
        \dd_trace_set_trace_id($headers['x-datadog-trace-id']);
        \dd_trace_push_span_id($headers['x-datadog-parent-id']);
    }

    \DDTrace\trace_function('app_entry_point', function ($s) {
        $s->service = getenv('DD_SERVICE') ?: getenv('DD_SERVICE_NAME');
        $s->type = 'web';
    });

    register_shutdown_function(function () {
        \dd_trace_pop_span_id();
    });
});

/* --- */

function app_startup()
{
    usleep(10);
}

function app_entry_point()
{
    usleep(500);
}

app_startup();
app_entry_point();
```

**Comment by ben-challis** [comment] 2021-05-21 11:41
@SammyK are there any updates on this? We're similarly struggling to see how we can implement distributed tracing through the new APIs where previously it was relatively hassle free via `dd_trace`.

**Comment by SammyK** [comment] 2021-05-21 14:24
@ben-challis I cannot provide an ETA at the moment, but we are actively working on unblocking the feature to add automatic distributed tracing support to internal spans (created with the sandbox API).

**Comment by ilazaridis** [comment] 2021-11-10 16:01
:eyes: on this one :)

**Comment by bwoebi** [comment] 2022-02-03 13:39
In release 0.70.0 (to be released in the next days), there has a new API added:
```php
set_distributed_tracing_context($trace_id, $parent_id, $origin = "", $tags = "")
```

That API can be called if there is no other currently active span.

in future it will be possible to also directly use `DDTrace\hook_function()`, set the distributed context there and start the span immediately within the hook. Please refer to #1358 for tracking this functionality.

I'm closing this issue as the actual issue here has been solved with the proper API introduced in 50b1e092b2555ccd27384be44a6b3413e68f1a4b.

**Closed by bwoebi** 2022-02-03 13:39 UTC
Labels: feature-request, cat:manual-instrumentation

**Comment by labbati** [comment] 2022-02-07 09:46
0.70.0 has been released

**Comment by iNviNho** [comment] 2022-06-07 11:15
Hi,

We are trying to set up distributed tracing and unfortunately, I can't reach the expected results.

We have a long-running process that processes messages. Before we process a message, we manually create a root span and after we process a message, we close the root span and flush it.

We tried to add the suggested `set_distributed_tracing_context` right before we manually created the tracer but that didn't help.

```php

....
// $traceId is the x-datadog-trace-id that we got from upstream service
// $parentId is the x-datadog-parent-id that we got from upstream service
set_distributed_tracing_context($traceId, $parentId);
        
$tracer = new Tracer();
GlobalTracer::set($tracer);

$resourceName = $topicName . '::process';

$options = ['start_time' => Time::now()];
$rootSpan = $tracer->startRootSpan(
    'Jobs',
    StartSpanOptions::create($options)
)
    ->getSpan();

$rootSpan->setTag(Tag::SPAN_TYPE, Type::CLI);
$rootSpan->setTag(Tag::SERVICE_NAME, 'broker.offer-service');
$rootSpan->setTag(Tag::RESOURCE_NAME, $resourceName, true);
$rootSpan->setTag('command_origin', $this->signature);

// add tracing for Producer::produce
trace_method(Producer::class, 'produce', function (SpanData $span) {
    $span->service = 'broker.offer-service.kafka';
});
.....
// process message
processMessage();

// flush 
GlobalTracer::get()->getRootScope()?->close();
GlobalTracer::get()?->flush();
```

Any idea what are we doing wrong?

Thank you

**Comment by bwoebi** [comment] 2022-06-07 12:16
Hey @iNviNho Trying with your snippet: nothing.

I just tried reproducing it and it works perfectly:
```
[{"uri":"\/v0.4\/traces","headers":{"Host":"request-replayer","Accept":"*\/*","Datadog-Meta-Lang":"php","Datadog-Meta-Lang-Interpreter":"cli","Datadog-Meta-Lang-Version":"8.0.17","Datadog-Meta-Tracer-Version":"1.0.0-nightly","Transfer-Encoding":"chunked","Content-Type":"application\/msgpack","X-Datadog-Trace-Count":"1"},"body":"[[{\"trace_id\":\"4231\",\"span_id\":\"9958183606787068397\",\"parent_id\":\"1234\",\"start\":1654603942200,\"duration\":244800,\"name\":\"Jobs\",\"resource\":\"test::process\",\"service\":\"broker.offer-service\",\"type\":\"cli\",\"meta\":{\"system.pid\":\"50910\",\"_dd.dm.service_hash\":\"832714b1a5\",\"_dd.p.dm\":\"832714b1a5-1\"},\"metrics\":{\"_dd.rule_psr\":1,\"_sampling_priority_v1\":1,\"php.compilation.total_time_ms\":65.778}},{\"trace_id\":\"4231\",\"span_id\":\"2544058407730743139\",\"parent_id\":\"9958183606787068397\",\"start\":1654603942903067500,\"duration\":14600,\"name\":\"Producer.produce\",\"resource\":\"Producer.produce\",\"service\":\"broker.offer-service.kafka\",\"type\":\"cli\"}]]"}]
```
This is the raw output I get using your snippet with a small amout of changes to get it to run at all standalone with hardcoded `$trace_id = 4321;` and `$parent_id = 1234;`.

As far as I can judge, it just works. Have you tried using `DD_TRACE_DEBUG=1`? Maybe there's something else going wrong. Also try checking the return value of `set_distributed_tracing_context` - it will return false if inputs are invalid for example.

**Comment by iNviNho** [comment] 2022-06-07 14:55
Thanks, @bwoebi for your answer.

I added more logging into our service and here are the logs:

We add a log right after we set distributed tracing:
```php
$result = set_distributed_tracing_context($traceId, $parentId);
Log::info('Set distributed tracing context', [
    'x-datadog-trace-id' => $traceId,
    'x-datadog-parent-id' => $parentId,
    'result' => (int)$result,
]);
```
output: 
```json
{
   "message":"Set distributed tracing context",
   "context":{
      "x-datadog-trace-id":"5760970482214493630",
      "x-datadog-parent-id":"106583421869774770",
      "result":1
   },
   "level":200,
   "level_name":"INFO",
   "channel":"staging",
   "datetime":"2022-06-07T14:37:08.232644+00:00",
   "extra":{
      
   },
   "dd":{
      "trace_id":"5760970482214493630",
      "span_id":"106583421869774770"
   }
}
```

And when application logs, I can see e.g. these logs:
```json
{
   "message":"Starting processing command",
   "context":{
      "user_id":"b738e8a4-849e-47ee-8158-2da9bef5ea4d",
      "trace_id":"9a40a61b-b93e-4a7f-beaf-92276ee1b400",
      "topic":"broker-trade-api-offer-create",
      "partition":5,
      "offset":106740
   },
   "level":200,
   "level_name":"INFO",
   "channel":"staging",
   "datetime":"2022-06-07T14:37:08.232869+00:00",
   "extra":{
      
   },
   "dd":{
      "trace_id":"106583421869774770",
      "span_id":"6733633495546298167"
   }
}
```

The dd part in the json is logged because of this line
```php
$context = \DDTrace\current_context();
$record['dd'] = [
    'trace_id' => $context['trace_id'],
    'span_id' => $context['span_id'],
];
```

So the question is, why did the **trace_id** change to the **parent_id**?

**Comment by bwoebi** [comment] 2022-06-07 16:23
This is a very good question :-)

I have no idea how these could get mixed up. I can give you a couple pointers to debugging though:

https://github.com/DataDog/dd-trace-php/blob/996cbf674351c8adf499e3bc3e8b047c2e98a4d1/src/DDTrace/Tracer.php#L104-L111
The Tracer API caches the distributed tracing context itself when it starts up.

https://github.com/DataDog/dd-trace-php/blob/996cbf674351c8adf499e3bc3e8b047c2e98a4d1/src/DDTrace/SpanContext.php#L29-L36
If we currently have no active spans, the Tracer API will reset the distributed tracing context to the current registered distributed ids. (like registered in the Tracer constructor (see above)) - These can be overwritten with `$options = ['child_of' => new SpanContext($traceId, $parentId, null, [], true)];`.

At least I suspect that this must be the locations where some things get messed up, but I cannot see how. I would truly appreciate some reproducer if possible :-)

To dump the spans without flushing to the backend, you can use `var_dump(dd_trace_serialize_closed_spans());`.
Also of interest can be the `distributed_tracing_parent_id` key from `\DDTrace\current_context()`.

**Comment by iNviNho** [comment] 2022-06-10 13:59
Hi @bwoebi ,

I did a few more tests and 

```php
^ "Given x-datadog-trace-id "
^ "123"
^ "Given x-datadog-parent-id"
^ "321"
$currentContext = \DDTrace\current_context();
dump('Current context before set_distributed_tracing_context ', $currentContext);
^ "Current context before set_distributed_tracing_context "
^ array:5 [
  "trace_id" => "0"
  "span_id" => "0"
  "version" => null
  "env" => "local"
  "distributed_tracing_propagated_tags" => []
]
$currentContext = \DDTrace\current_context();
dump('Current context after set_distributed_tracing_context ', $currentContext);
^ "Current context after set_distributed_tracing_context "
^ array:6 [
  "trace_id" => "123"
  "span_id" => "321"
  "version" => null
  "env" => "local"
  "distributed_tracing_parent_id" => "321"
  "distributed_tracing_propagated_tags" => []
]

$tracer = new Tracer();
GlobalTracer::set($tracer);
$options = ['start_time' => Time::now()];
$rootSpan = $tracer->startRootSpan(
    'Jobs',
    StartSpanOptions::create($options)
)
    ->getSpan();
^ "Current context after new tracer set_distributed_tracing_context "
^ array:6 [
  "trace_id" => "123"
  "span_id" => "321"
  "version" => null
  "env" => "local"
  "distributed_tracing_parent_id" => "321"
  "distributed_tracing_propagated_tags" => []
]
trace_method(
    OfferService::class,
    'processOfferCreateCommand',
    function (SpanData $span) {
        $span->service = 'broker.offer-service';
    }
);
^ "dd_trace_serialize_closed_spans before flush"
^ array:1 [
  0 => array:10 [
    "trace_id" => "321"
    "span_id" => "12120054209781092652"
    "parent_id" => "12824553535804673670"
    "start" => 1654869196594195365
    "duration" => 58487
    "name" => "App\Services\OfferService.processOfferCreateCommand"
    "resource" => "App\Services\OfferService.processOfferCreateCommand"
    "service" => "broker.offer-service"
    "type" => "cli"
    "meta" => array:1 [
      "env" => "local"
    ]
  ]
]

```

So out of these logs, I have 2 questions:
- Why is distributed_tracing_parent_id 321 and not 123?
- Why is trace_id 321 and not 123 in serialized closed span? Why is parent_id 12824553535804673670? Should it be 123?

**Comment by bwoebi** [comment] 2022-06-10 14:41
Ah @iNviNho, if you're on 0.73.0 you really should upgrade to 0.74.0, which includes https://github.com/DataDog/dd-trace-php/pull/1571 and https://github.com/DataDog/dd-trace-php/pull/1564.

Both of which could be beneficial to your concrete use case.

When using the DDTrace\Tracer API, and changing your distributed trace context, you must create a new Tracer instance.
To reset the distributed tracing context, call `set_distributed_tracing_context(0, 0);`.

**Comment by bwoebi** [comment] 2022-06-10 14:46
And I just figured: https://github.com/DataDog/dd-trace-php/pull/1586 (included in 0.74.0) fixes a bug that overwrites the trace_id under some circumstances. That's why you were getting bad information here :-/

I was looking at 0.74.0 code, and hence confused by your reports.

**Comment by iNviNho** [comment] 2022-06-10 14:48
@bwoebi oh, my bad, i was under impression we have latest version :( 

Would this be the correct method that starts datadog tracing everytime we get a new message?

```php
protected function startDatadogTracing(
        string $topicName,
        string $traceId = null,
        string $parentId = null
    ): void
    {
        set_distributed_tracing_context(0, 0);
        $tracer = new Tracer();
        GlobalTracer::set($tracer);
        if (!empty($traceId) && !empty($parentId)) {
            $result = set_distributed_tracing_context($traceId, $parentId);
            Log::info('Set distributed tracing context', [
                'x-datadog-trace-id' => $traceId,
                'x-datadog-parent-id' => $parentId,
                'result' => (int)$result,
            ]);
        }
        ...
    }
```

?

**Comment by iNviNho** [comment] 2022-06-10 15:25
Unfortunately, it doesn't work.

When processing second message with trace_id => 456 and parent_id 654, I can see that my current context is
```php
 array:6 [
  "trace_id" => "456"
  "span_id" => "654"
  "version" => null
  "env" => "local"
  "distributed_tracing_parent_id" => "654"
  "distributed_tracing_propagated_tags" => []
]
```

but when I serialize closed spans, I still see the first trace_id :( 

```php
^ array:1 [
  0 => array:10 [
    "trace_id" => "123"
    "span_id" => "10361178268955270783"
    "parent_id" => "7563426945992603363"
    "start" => 1654872762988647902
    "duration" => 814229
    "name" => "App\Services\OfferService.processOfferCreateCommand"
    "resource" => "App\Services\OfferService.processOfferCreateCommand"
    "service" => "broker.offer-service"
    "type" => "cli"
    "meta" => array:1 [
      "env" => "local"
    ]
  ]
]
```

Can I somehow manually set rootContext of Tracer object?

**Comment by bwoebi** [comment] 2022-06-10 15:36
I'm somehow suspecting that something else in your code is going wrong on your end, especially that I cannot reproduce any issue locally.

I'd like to invite you to reach out to us privately (via support ticket asking for a call, referring this message or directly to me on our public slack) so that we can debug that issue.

**Comment by iNviNho** [comment] 2022-06-10 15:45
:partying_face:  :partying_face:  :partying_face: 

After debugging locally and removing set_distributed_tracing_context after Tracer has been created, distributed tracing works correctly even in long running CLI command.

Final code

```php
protected function startDatadogTracing(
        string $topicName,
        string $traceId = null,
        string $parentId = null
    ): void {
        if (!empty($traceId) && !empty($parentId)) {
            $result = set_distributed_tracing_context($traceId, $parentId);
            Log::info('Set distributed tracing context', [
                'x-datadog-trace-id' => $traceId,
                'x-datadog-parent-id' => $parentId,
                'result' => (int)$result,
            ]);
        }

        $tracer = new Tracer();
        GlobalTracer::set($tracer);

        $resourceName = $topicName . '::process';

        $options = ['start_time' => Time::now()];
        $rootSpan = $tracer->startRootSpan(
            'Jobs',
            StartSpanOptions::create($options)
        )
            ->getSpan();

        $rootSpan->setTag(Tag::SPAN_TYPE, Type::CLI);
        $rootSpan->setTag(Tag::SERVICE_NAME, 'broker.offer-service');
        $rootSpan->setTag(Tag::RESOURCE_NAME, $resourceName, true);
        $rootSpan->setTag('command_origin', $this->signature);
    }
```

THank you @bwoebi for your help!!!

**Comment by bwoebi** [comment] 2022-06-10 15:53
Glad I could help you :-)
