### ISSUE TITLE
Causing PDO errors in our application

### ISSUE THREAD

**Issue by jonners99** [DataDog/dd-trace-php#451] opened 2019-05-24 09:57 UTC
We are evaluating on a dev server, we have noticed an increased number of exceptions since installing dd-trace-php. All like the following: 

`[24-May-2019 10:43:52 Europe/London] PHP Fatal Error: (See Admin Error Log for full details) PDOException: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
{"message":"Uncaught exception","context":{"exception":{"class":"PDOException","message":"SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.","code":"HY000","file":"/opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/PDO/PDOIntegration.php:269"}},"level":500,"level_name":"CRITICAL","channel":"exception","datetime":{"date":"2019-05-24 10:43:52.530095","timezone_type":3,"timezone":"Europe/London"},"extra":[]}`

For now I have disabled monitoring of PDO, which has resolved the issue. But obviously this means we are not receiving PDO data.

PHP 5.6, MySQL 5.5, CentOS7

**Comment by labbati** [comment] 2019-05-24 10:10
Hi @jonners99 sorry for the issue. We have been made aware of a similar issue and based on an early investigation we recently performed it may be related to one of two scenarios if you are using the default 'buffered' mode. Stored procedures and queries against sphinx. Can you please provide more info about your use case?

Ideally it would be great if you can provide a code snippet that reproduces the query causing the issue so we can run/test in our local env.

In the meantime, if you still are interested in evaluating our tracer, feel free to disable PDO integration: `DD_INTEGRATIONS_DISABLED=pdo`

**Comment by ananth-iyer** [comment] 2019-06-11 09:49
@labbati Can I set this environment variable in PHP code? `DD_INTEGRATIONS_DISABLED=pdo`

**Comment by labbati** [comment] 2019-06-12 14:08
No it is too late then. Please follow these instructions: https://docs.datadoghq.com/tracing/setup/php/#configuration

**Comment by carflo** [comment] 2019-06-17 19:41
+1 
We are getting the same error message with 0.27.2 using stored procs. Setting `DD_INTEGRATIONS_DISABLED=pdo` gets rid of the error so the issue lies in there.

```
PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. in /opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/PDO/PDOIntegration.php:269
```

Thank you!

**Comment by pierophp** [comment] 2019-06-19 19:29
Hi,

I'm facing a similar problem:

SQLSTATE[HY000] [2002] Connection timed out {"trace":"#0 [internal function]: PDO->__construct('mysql:host=mysq...')\n#1 /opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/PDO/PDOIntegration.php(86): dd_trace_forward_call()

This happens around 50 times a day on our production env

Thank you

**Comment by jonners99** [comment] 2019-07-08 08:56
"Ideally it would be great if you can provide a code snippet that reproduces the query causing the issue"

Unfortunately its a little tied into business logic but we are using stored procedures so that is potentially where the problem lies.

**Comment by pawelchcki** [comment] 2019-08-23 11:11
Thank you for your patience.
We've just released version https://github.com/DataDog/dd-trace-php/releases/tag/0.30.1 Which fixes timely freeing of out of scope object/resources. Which has improved how PDO connections are handled when tracer is enabled.

Looking at your bug report this has high chance of solving your issue. 

Let us know if after upgrading to 0.30.1 this problem still exists.

**Comment by carflo** [comment] 2019-09-03 16:27
@pawelchcki upgrading to [0.30.1](https://github.com/DataDog/dd-trace-php/releases/tag/0.30.1) resolved the issue for us. Thank you!

**Comment by labbati** [comment] 2019-09-04 07:58
Thanks @carflo for confirming. @jonners99 did you have a chance to test the new version in your environment? I would be great to know if it resolved the issue for you too.

**Comment by labbati** [comment] 2019-09-17 09:01
Hi @jonners99, I am closing this issue as it should be fixed. Please feel free to reopen if the issue is not resolved for you.

**Closed by labbati** 2019-09-17 09:01 UTC
