### ISSUE TITLE
[Feature] Allow a way to remove some spans from default integrations

### ISSUE THREAD

**Issue by khepin** [DataDog/dd-trace-php#966] opened 2020-07-16 22:08 UTC
**Is your feature request related to a problem? Please describe.**
The default laravel tracing of every single `event` becomes problematic when loading large amounts of models. Here's an example of a trace:

![Screen Shot 2020-07-16 at 2 59 49 PM](https://user-images.githubusercontent.com/455656/87727139-4327bc00-c775-11ea-9746-c748ca01e6c3.png)

This query retrieves ~200 models and later on, we retrieve models attached to each of those models, which very rapidly brings us into the thousands of spans which are all of the type `laravel.event.handle` which in our case are not valuable to trace and bring us over the limit of 999 spans per trace.

**Describe the solution you'd like**
Since I seem to be able to replace the default handler for tracing those methods, I'd like to be able to disable it entirely as well and have no span created.

Potentially, this should be part of the `SpanData` itself so that we could keep some events while ignoring others though we don't have a use case for this at the moment.

**Describe alternatives you've considered**
Here's everything I've tried: 
```php
\dd_trace_method('Illuminate\Events\Dispatcher', 'fire', function() {});
\dd_trace_method('Illuminate\Events\Dispatcher', 'fire', null);
\dd_trace_method('Illuminate\Events\Dispatcher', 'fire', false);
\dd_trace_method('Illuminate\Events\Dispatcher', 'fire');
\dd_trace_method('Illuminate\Events\Dispatcher', 'fire', function ($span) {
    $span->setTag(\DDTrace\Tag::MANUAL_DROP, true);
});
```
The final alternative would be to not use the Laravel integration at all and rebuild it on our own. Which isn't a great solution in my opinion.

**Additional context**
Nope

**Comment by khepin** [comment] 2020-07-16 22:11
![image](https://user-images.githubusercontent.com/455656/87727752-7ae33380-c776-11ea-8dba-f5d24e0b87ff.png)
This is all I've been able to get when setting the trace handler to `false` or `null`

**Comment by morrisonlevi** [comment] 2020-07-16 22:57
You can choose to drop a span by using returning `false`, but there are some issues with it because it effectively orphans (or drops) all its children spans too. If that's a side-effect you can live with then that's your work-around.

A month or so ago I put in a feature request for being able to drop these kinds of things more reliably for exactly the kind of use case you see here! It hasn't been scheduled, but I'll be sure that it's brought up at the next planning meeting to see when we think we can schedule it.

**Comment by khepin** [comment] 2020-07-16 23:05
Sweet! we can live with that in this case so I'll move forward with that solution. Greatly appreciate your help.

**Comment by labbati** [comment] 2020-09-09 10:37
closing this issue as the solution proposed by Levi fixes the issue.

**Closed by labbati** 2020-09-09 10:37 UTC
Labels: feature-request

**Comment by kirkbushell** [comment] 2024-07-02 02:30
> closing this issue as the solution proposed by Levi fixes the issue.

It doesn't fix it, it's a workaround with a caveat that is potentially damaging.

We need (imho) the ability to configure what is actually recorded by datadog. We have the exact same issue.

**Comment by acarpio89** [comment] 2024-07-03 09:33
@morrisonlevi I was hoping you could help us out on this one. We need to exclude `eloquent.retrieved` events because some requests have hundreds of these and we quickly reach the 1000 spans limit.

We're adding this to our code following the suggestion in this thread:
```
\DDTrace\trace_method(
    'Illuminate\Events\Dispatcher',
    'dispatch',
    function (\DDTrace\SpanData $span, array $args) {
        return false;
    }
);
```
but still getting all those `eloquent.retrieved` spans that we want to ignore:

<img width="307" alt="Screenshot 2024-07-03 at 7 23 25 PM" src="https://github.com/DataDog/dd-trace-php/assets/12226290/c89e3e78-af5b-474f-9454-6577318b33f6">

I've added logging inside the closure and I can confirm it's running. I've also inspected the `$args` array and have been able to pinpoint the `eloquent.retrieved` events specifically, but returning false does not seem to drop them. 

Do you have any suggestions?

**Comment by onigra** [comment] 2024-10-03 04:41
I have the same problem. I hope this issue will be reopened.

**Comment by barrycommins** [comment] 2024-11-25 19:06
Have the same issue.

I would have expected `DD_TRACE_ELOQUENT_ENABLED: false` to remove the spans, but it doesn't seem to.

https://docs.datadoghq.com/tracing/trace_collection/library_config/php/#integration-names
