### ISSUE TITLE
[BUG] Increased memory usage/leak after upgrading from 0.64.1 to 0.67.0+

### ISSUE THREAD

**Issue by olsavmic** [DataDog/dd-trace-php#1545] opened 2022-03-21 15:23 UTC
### Bug description

We are seeing memory usage typical for memory leaks on one of our apps with PHP 8.1 running and DDTrace versions 0.67.0, 0.68.2, 0.69.0 (we were not able to test 0.70+ due to reported issue https://github.com/DataDog/dd-trace-php/issues/1544) after upgrading from DDTrace 0.64.1 on long-running processes (mainly queue consumers).

In order to investigate further what is happening, we updated a second application (running PHP 8.0) also from DDTrace 0.64.1 to 0.69.0 and we can see non-negligible memory usage increase although I cannot say for sure it's a memory leak or just an increase in memory footprint since we're scaling the application a lot and therefore lifetime of a container is in matter of minutes, not hours.

I've seen that DDTrace started to use WeakRef/WeakMap on PHP 8.0+. I'm not sure if it's somehow related but we encountered issues with WeakRef that is reported and verified here: https://bugs.php.net/bug.php?id=81027.

We're also heavily using Guzzle in many of the consumers that now fail on memory. 

I'd love to provide more information but I'm not sure how to debug ddtrace memory usage properly, especially when it exhibits only in long-running processes (I may try Blackfire but it's not easy to replicate the "traffic" locally).

I'm also not entirely sure it's DDTrace fault but as I said nothing had been changed on the second application except for DDTrace version and increased memory usage is clearly visible.

I'd appreciate any insight into what MIGHT have changed, any debugging tips and if an increased memory usage is expected or not.

Thank you!

<img width="515" alt="Screenshot 2022-03-18 at 11 46 43 (1)" src="https://user-images.githubusercontent.com/3778875/159289715-a43273eb-ae56-4566-9969-008fc2a1c214.png">
(First application, showing average memory usage)

<img width="1650" alt="Screenshot 2022-03-21 at 16 05 33" src="https://user-images.githubusercontent.com/3778875/159290131-5f2d9a4a-764c-4e3f-8267-4c45a745ca30.png">
(Second application, nothing had been changed here except for DDTrace version, showing average memory usage, aggregated from multiple containers)

increased memory usage on our application running

### PHP version

```
PHP 8.1.4 (cli) (built: Mar 20 2022 16:51:10) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.4, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.4, Copyright (c), by Zend Technologies
    with blackfire v1.75.0~linux-x64-non_zts81, https://blackfire.io, by Blackfire
    with ddtrace v0.71.0, Copyright Datadog, by Datadog
```
### Tracer version

0.69.0

### Installed extensions

```
[PHP Modules]
bcmath
blackfire
calendar
Core
ctype
curl
date
ddtrace
dom
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
igbinary
imagick
imap
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
blackfire
ddtrace
```
### OS info

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
```
#### Output of phpinfo() (ddtrace >= 0.47.0)
```json
{"date":"2022-03-21T14:27:48Z","os_name":"Linux f2f9e7dc8456 5.10.104-linuxkit #1 SMP Wed Mar 9 19:05:23 UTC 2022 x86_64","os_version":"5.10.104-linuxkit","version":"0.71.0","lang":"php","lang_version":"8.1.4","env":"olsavmic","enabled":true,"service":"testing-71","enabled_cli":true,"agent_url":"http:\/\/datadog:8126","debug":true,"analytics_enabled":false,"sample_rate":1,"sampling_rules":[],"tags":[],"service_mapping":[],"distributed_tracing_enabled":true,"priority_sampling_enabled":true,"dd_version":null,"architecture":"x86_64","sapi":"fpm-fcgi","datadog.trace.request_init_hook":"\/opt\/datadog-php\/dd-trace-sources\/bridge\/dd_wrap_autoloader.php","open_basedir_configured":false,"uri_fragment_regex":null,"uri_mapping_incoming":null,"uri_mapping_outgoing":null,"auto_flush_enabled":false,"generate_root_span":true,"http_client_split_by_domain":false,"measure_compile_time":true,"report_hostname_on_root_span":false,"traced_internal_functions":null,"auto_prepend_file_configured":false,"integrations_disabled":"default","enabled_from_env":true,"opcache.file_cache":null}
```

Diagnostic checks | passed

### Upgrading info

Upgraded from DDTrace 0.64.1 -> 0.67.0, 0.68.2, 0.69.0, all versions are showing the same behaviour.

**Comment by labbati** [comment] 2022-03-29 08:17
Hi @olsavmic, thank you for the details and my apologies for the late reply. We are currently investigating it, I will provide updates as soon as possible. For a start, this increase is not 'normal', or at least it was not found by our reliability environment (apps that we run 24/7 indefinitely to check for memory leaks etc...).

**Comment by labbati** [comment] 2022-03-30 09:55
I wanted to provide a quick update as the investigation continues. We added 8.1.4 to our test suites (https://github.com/DataDog/dd-trace-php/pull/1551) and so far no memory leak was noticed for long running script, that is what basically a "mainly queue consumers" should look like. Both with and without Bob's fix on https://github.com/DataDog/dd-trace-php/pull/1550.

We will keep investigating and provide you with more updates.

**Comment by ComiR** [comment] 2022-03-30 14:08
We're also having the same problem with a massive increase in memory usage with PHP 7.4.28 and version 0.70.1.
Our version was 0.53.0 before. We also tried 0.64.1 (which was the the base version for @olsavmic) but had unusual high memory usage too, so this problem seems to get even more interesting to debug. 😅

<img width="1050" alt="Memory usage" src="https://user-images.githubusercontent.com/11410095/160853428-d4b5a544-145a-414e-afa0-8bf2a4359cfe.png">
The whole graph covers a span of about two weeks and the colored vertical bars represent the deployments of versions 0.70.1, 0.64.1 and 0.53.0 respectively.

**Comment by ComiR** [comment] 2022-03-31 10:21
![RAM Request, Limit and Usage](https://user-images.githubusercontent.com/11410095/161033432-b7d9ae93-45c1-4cf6-9fa0-c2525e75ab6d.png)

**Comment by labbati** [comment] 2022-04-01 09:06
Thank you @ComiR, I have a couple of questions:

- Does those numbers (24GB) add up with your system, I mean does your container/pod/host have that quantity of memory available?
- Can you describe your application? E.g. any async frameworks (that we do not support) like openswoole, or extensions like pctnl? Actually could you also print the output of `php -m`?
- How do you configure tracing for long running scripts? Specifically do you follow the approach recommended in https://docs.datadoghq.com/tracing/setup_overview/setup/php/?tab=containers#long-running-cli-scripts (manually trace the repetitive function + long-running scripts environment variables).

@olsavmic and @ComiR I would be open to have a live session with you, we can schedule a call (or I could even jump into a call without early scheduling). It might help to take a look at your manual tracing and at your system, if that can help me reproduce the issue. If you are open to that feel free to reach out for me on the public datadog slack or to open a ticket and refer to this message.

So far here is my current status update on the investigation.

Within short sessions (5-6 minutes each I do not see any drift (like a memory leak) with (A) 0.71.0, (B) no tracing at all and (C) 0.69.1. Everything looks good. I am using an app that generates random execution paths that include all our library instrumentation, randomly generating many traces ranging from a few spans to tens of spans for each repetition (like in a long running script). With this app, typically, if there is a drift/leak is visible in tens of seconds because it does continuosly a whole bunch of strange things.

![image](https://user-images.githubusercontent.com/2952352/161231456-5655ffb8-c9d1-4f54-b6a2-394c7f22244e.png)

In any case, and just to be sure, I am running 0.69.0 on PHP 8.1.4 for 30 mins now, and nothing stands out, I will keep running for a while and see.

At this point I think that there is a combination of factors, and I might need a more involved help from you to get to a reproduction case.

**Comment by labbati** [comment] 2022-04-01 10:14
An additional question, what is the ram usage for? An host (with several processes), a container, k8s?

**Comment by mtreuberg** [comment] 2022-04-01 14:58
@labbati That ram usage from @ComiR in https://github.com/DataDog/dd-trace-php/issues/1545#issuecomment-1084379816 is the max() usage of all pods in a single k8s deployment

**Comment by labbati** [comment] 2022-04-04 15:59
Right now we are short of ideas to test on our end. Moreover we attempted a quite a few combinations and there is a high probability, I believe, that this excessive memory usage is caused by the tracer not supporting well something that your applications are doing with manual tracing or configuration, or a combination of the two.

I propose that you open tickets referring this issue/comment, so from there we can schedule a call, if you are open to that, and we can take a look at your code  manual instrumentation to understand if something stands out.

**Comment by mtreuberg** [comment] 2022-04-05 07:04
@labbati We figured out that we weren't really using the tracing anymore - APM is deactivated in DataDog. Only the code and extension are still there. That's why we removed the extension which then leads to the `NoopTracer` being used.

Just as a hint what might have caused it:
```
// This is an excerpt of the legacy app where we had the tracing in.
// This is a Zend1 Action Plugin

use DDTrace\GlobalTracer;
use DDTrace\Integrations\ZendFramework\V1\TraceRequest;
use DDTrace\Tag;

class DataDogTrace extends TraceRequest
{
	public function preDispatch(\Zend_Controller_Request_Abstract $request)
	{
		$scope = GlobalTracer::get()->getRootScope();
		if (null === $scope) {
			return;
		}

		$span       = $scope->getSpan();
		$module     = $request->getModuleName();
		$span->setTag('zf1.module', $module);
		// ... set some more tags
		$span->setTag('requestId.root', Url::getUniqueRequestId());
	}

	public function postDispatch(\Zend_Controller_Request_Abstract $request)
	{
		$scope = GlobalTracer::get()->getRootScope();
		if (null === $scope) {
			return;
		}
		$scope->getSpan()->setTag(Tag::HTTP_STATUS_CODE, $this->getResponse()->getHttpResponseCode());
	}
}
```

In addition to that, there were a handful of locations similar to this one:
```
		$span = GlobalTracer::get()->startActiveSpan('view.helper.abstractViewHelper.renderPartial')->getSpan();
		$span->setTag('name', $name);
		// ... do something
		$span->finish();
```

So we won't dig into this issue any deeper but thank you very much for trying to solve the problem quickly!

**Comment by olsavmic** [comment] 2022-04-05 13:57
@labbati Thanks for your efforts!

I was able to isolate our instrumentation and found out that one of possible reasons our app leaks memory is the following code:

```php
function traceConsumer(){
    if ($tracer->getActiveSpan() !== null) {
        $this->resetTracer();
        $scope = $this->startRootSpan('');
    } else {
        $scope = $this->startActiveSpan('');
    }
```

in case there is some active span (which should not be the case since `DD_TRACE_GENERATE_ROOT_SPAN= false` but it may occur due to some combination of manual/automatic instrumentation - I was not able to reproduce that yet), the `resetTracer` function is never called.

The important part of `resetTracer` is actually calling `$tracer->reset()` which clears the scopeManager and mainly the **array of $traces**

If you try the following code and remove the `$tracer->reset()` call, it'll leak memory which goes against the recommendation in https://github.com/DataDog/dd-trace-php/issues/1533#issuecomment-1059256992.

```php
$tracer = GlobalTracer::get();

for($i = 0; $i < 100000; $i++) {
    $scope = $tracer->startActiveSpan('span');

    $span = $scope->getSpan();
    $span->finish();
    $scope->close();

    $tracer->flush();
    $tracer->getScopeManager()->close();
    $tracer->reset(); // Without this call, memory leaks for all versions

    gc_collect_cycles();
    print_r(memory_get_usage());
    echo PHP_EOL;
}
```

We'll try to overwrite the root span every time (including reset of the tracer) and I'll post you with more updates after 0.71.2 with fix for https://github.com/DataDog/dd-trace-php/issues/1544 is released :)

**Comment by bwoebi** [comment] 2022-04-05 15:13
Hey @olsavmic - thanks for investigating on your end!

With 0.70+ the `$tracer->reset()` call is doing nothing important anymore. Since 0.63.0 it lost more and more things to internal.

If your code is leaking memory here this means that there's an unbalanced amount of span opening and closing.
In that case it is likely that the root cause is within your manual instrumentation.

The proper way to reset the tracer now as mentioned in that issue is (since 0.66.0 - between 0.66.0 and 0.70.0 exclusively you additionally need the `GlobalTracer->reset()` call):

```php
ini_set("datadog.tracer.enabled", 0);
ini_set("datadog.tracer.enabled", 1);
```

I'd like to note that this (just like `GlobalTracer->reset()` previously) will loose all in-flight spans. If you replace the `$tracer->reset()` your test case here with the double `ini_set` it should not leak either.

To debug this issue in your application, at this place right before you call `$this->resetTracer()` right now, i.e. where you usually assume that there's no active span left do something like:
```php
if (\DDTrace\active_span()) {
    print "Still active span on the stack:\n";
    var_dump(\DDTrace\active_span());
    print "Closed spans:\n"
    var_dump(\DDTrace\dd_trace_serialize_closed_spans());
}
```
With that information you can analyze which spans were started, and given that, verify whether all these locations where a span was started have a corresponding call to close the spans.

If you have further questions here, I'm also open to being contacted via direct message in the public datadog slack.

We plan on releasing 0.72.0 as soon as possible.

**Comment by bwoebi** [comment] 2022-04-07 12:22
Hey @olsavmic 0.72.0 is out now with the fix for #1544. Can you please retry and verify whether your memory leaks come indeed from unfinished spans? Thanks!

**Comment by mtokioka** [comment] 2022-04-13 05:17
FYI
We had memory leak with version 0.71.1, and php7.4.29.
We use datadog with custom instrumentation almost like this code https://github.com/DataDog/dd-trace-php/issues/916#issuecomment-879029681 
or just call `getActiveSpan()`.
After updating 0.72.0, memory leak disappear.

**Comment by olsavmic** [comment] 2022-04-19 11:08
@bwoebi Thank you for these changes! We are running 0.72 now although the memory still continues to leak.

I tried your tip with `ini_set('datadog.tracer.enabled')` but I've got few issues:

1. ~~I think it's actually `ini_set('datadog.trace.enabled')` (https://github.com/DataDog/dd-trace-php/pull/1564#discussion_r852905342)~~ (will be resolved as commented)

2. Is the instance returned by `GlobalTracer::get()` overwritten by calling ini_set('datadog.trace.enabled', '0'), ini_set('datadog.trace.enabled', '1')? It looks like it's not (the object has the same spl_object_id after reset).

3. Code like this gives a segfault (at least on PHP 8.1.5, ddtrace 0.72)

```php
<?php declare(strict_types = 1);

use DDTrace\GlobalTracer;

(static function (): void {
    require_once dirname(__DIR__) . '/vendor/autoload.php';

    \DDTrace\trace_function(
        'someOtherMethod',
        function (): void {
            \DDTrace\root_span();

            echo 'ok2';
        },
    );

    function someOtherMethod()
    {
        echo 'some other method called' . PHP_EOL;
    }

    function test()
    {
        for ($i = 0; $i < 1000; $i++) {
            echo "Iteration: {$i}" . PHP_EOL;
            $tracer = GlobalTracer::get();
            $scope = $tracer->startRootSpan('wat');

            someOtherMethod();

            gc_collect_cycles();

            print_r(memory_get_usage());
            echo PHP_EOL;

            $span = $scope->getSpan();
            $span->finish();
            $scope->close();
            $tracer->flush();

            $tracer->reset();
            ini_set('datadog.trace.enabled', '0');
            ini_set('datadog.trace.enabled', '1');
        }
    }

    test();
})();
```

Output:
```
root@89b6f1ecc476:/# php app/public/index-mem.php 
[2022-04-19T11:00:48+00:00] [ddtrace] [debug] - Attempting integrations load
[2022-04-19T11:00:48+00:00] [ddtrace] [debug] - Loaded integration web
[2022-04-19T11:00:48+00:00] [ddtrace] [debug] - Integration codeigniter not loaded. New attempts might be performed.
[2022-04-19T11:00:48+00:00] [ddtrace] [debug] - Loaded integration curl
[2022-04-19T11:00:48+00:00] [ddtrace] [debug] - Loaded integration eloquent
[2022-04-19T11:00:48+00:00] [ddtrace] [debug] - Integration guzzle not loaded. New attempts might be performed.
[2022-04-19T11:00:48+00:00] [ddtrace] [debug] - Integration laravel not loaded. New attempts might be performed.
[2022-04-19T11:00:48+00:00] [ddtrace] [debug] - Integration mysqli not available. New attempts WILL NOT be performed.
[2022-04-19T11:00:48+00:00] [ddtrace] [debug] - Loaded integration symfony
Iteration: 0
some other method called
ok21860944
[2022-04-19T11:00:48+00:00] [ddtrace] [debug] - Flushing 0 traces, 2 spans
Successfully triggered flush with trace of size 2
Iteration: 1
some other method called
Could not init tracing closure
1853176
[2022-04-19T11:00:48+00:00] [ddtrace] [debug] - Flushing 0 traces, 2 spans
Successfully triggered flush with trace of size 1
Iteration: 2
some other method called
Could not init tracing closure
1853176
[2022-04-19T11:00:48+00:00] [ddtrace] [debug] - Flushing 0 traces, 2 spans
Successfully triggered flush with trace of size 1
Iteration: 3
some other method called
1853176
[2022-04-19T11:00:48+00:00] [ddtrace] [debug] - Flushing 0 traces, 1 spans
Successfully triggered flush with trace of size 1
Iteration: 4
Segmentation fault
```

**Comment by bwoebi** [comment] 2022-04-19 11:18
I can confirm the segfault on PHP 8. (PHP 7 doesn't crash.)
I'll fix it as soon as possible.

**Comment by bwoebi** [comment] 2022-04-19 12:37
While PHP 7 doesn't crash, on PHP 7 callbacks installed via hook/trace_function/method are reset upon GlobalTracer->reset(). They shouldn't be. I'm fixing this.

Regarding your other question @olsavmic: Yes, the GlobalTracer object is not changed. There's no actual reason to, just internal state is reset essentially.

**Comment by bwoebi** [comment] 2022-05-12 13:40
@olsavmic 0.74.0 has been released. The way resetting is handled now, your memory probably should not leak anymore either.

**Closed** 2022-07-05 09:25 UTC
Labels: 🐛 bug, sev-1, cat:performance

**Comment by olsavmic** [comment] 2022-08-08 16:33
@labbati FYI We found out that the main cause of the memory leak was https://github.com/php/php-src/issues/9266. Thank you for all the debugging and fixing all the stuff we came across in the meantime :)

**Comment by bwoebi** [comment] 2022-08-08 17:42
This is insidious. But thanks for reporting back :-)
