### ISSUE TITLE
[BUG] 502 Bad Gateway after upgrading to 0.68

### ISSUE THREAD

**Issue by rodehoed** [DataDog/dd-trace-php#1433] opened 2021-12-29 09:45 UTC
### Bug description
After updating to datadag-tracer 0.68 all PHP applications stop working.

### PHP version
8.0.13 and 7.4

### Installed extensions
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
json
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
ddtrace

### OS info
RHEL 7.9

### Diagnostics and configuration
After upgrading to 0.68 PHP scripts seems to hang and causing 502. Even a simple phpinfo script. I also disabled selinux (just to be sure) and doesn't make a difference.

#### Output of phpinfo() (ddtrace >= 0.47.0)
Not possible. It's not processing.

### Upgrading info
I have updated from 0.48 *sigh*

**Comment by rodehoed** [comment] 2021-12-29 10:09
I did some testing, but when I downgrade to 0.67 it works again. 

When I disable the application (Symfony I believe) and load the phpinfo.php it works with 0.68. But when I enable Symfony again, it stop working again (also the phpinfo.php). So I might be caused by the application.

**Comment by krakjoe** [comment] 2021-12-29 10:09
If you can install debug symbols (help [here](https://docs.datadoghq.com/tracing/setup_overview/setup/php/?tab=containers#install-debug-symbols)), please provide a backtrace of the crash.

You may obtain a trace via CLI, it will likely crash in the same way, if you just execute `php -m`

If you are not able to install debug symbols or obtain a backtrace, we may be able to provide you with a build including a possible fix: We have just investigated a bug that exhibits the same symptoms and the fix is in the process of review.

**Comment by rodehoed** [comment] 2021-12-29 10:18
Hi @krakjoe 

Thanks for the fast response. Debugging it is not possible in this case. But i'm willing to test the test release.

**Comment by krakjoe** [comment] 2021-12-29 10:54
The following artifacts from the latest build of master (which contain a potential fix, I hope) may be obtained from:

   - https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/7096/workflows/5cb74494-413b-4ae1-8999-7dd7b284129e/jobs/826493/artifacts#:~:text=datadog%2Dphp%2Dtracer_1.0.0%2Dnightly_noarch.apk
   - https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/7096/workflows/5cb74494-413b-4ae1-8999-7dd7b284129e/jobs/826493/artifacts#:~:text=datadog%2Dphp%2Dtracer_1.0.0%2Dnightly_amd64.deb
   - https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/7096/workflows/5cb74494-413b-4ae1-8999-7dd7b284129e/jobs/826493/artifacts#:~:text=datadog%2Dphp%2Dtracer%2D1.0.0_nightly%2D1.x86_64.rpm
   - https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/7096/workflows/5cb74494-413b-4ae1-8999-7dd7b284129e/jobs/826493/artifacts#:~:text=datadog%2Dphp%2Dtracer%2D1.0.0%2Dnightly.x86_64.tar.gz

Choose the correct package based on your current installation method.

Please deploy this to a development or staging environment, not production.

We await feedback, thanks for patience ;)

**Comment by rodehoed** [comment] 2021-12-29 11:13
I tried the nightly build, but the problem remains.

**Comment by labbati** [comment] 2021-12-29 13:13
@rodehoed would you be open to a debugging session in your staging environment in case "Debugging it is not possible in this case" does not apply there? Without a backtrace there is not much we can do at this point.

If you are open to, please reach out to me on our [public Slack](https://datadoghq.slack.com/) (my handle is `luca.abbati`) and we can coordinate for a Zoom call.

**Comment by rodehoed** [comment] 2022-01-03 07:34
Best wishes first of all! It's strange because I cannot reproduce the behaviour on the development environment. Software stack is identical; db content and visitor load is ofcourse different.

**Comment by negoziator** [comment] 2022-01-04 14:30
I have experienced the exact same problem.*

Tried with both php `8.0`, `8.1.0` and `8.1.1`.

I'm not sure of this only happens if you are using Apache 2.4.x

I just downgraded to `0.67` and it all works like a charm again.

**Comment by krakjoe** [comment] 2022-01-04 16:03
The following artifacts from the latest build of master may contain a fix: We are stabbing in the dark a little without backtraces and or reproducing code, we appreciate your patience :)

  - https://842638-119990860-gh.circle-artifacts.com/0/datadog-php-tracer-1.0.0-nightly.x86_64.tar.gz
  - https://842638-119990860-gh.circle-artifacts.com/0/datadog-php-tracer-1.0.0_nightly-1.x86_64.rpm
  - https://842638-119990860-gh.circle-artifacts.com/0/datadog-php-tracer_1.0.0-nightly_amd64.deb
  - https://842638-119990860-gh.circle-artifacts.com/0/datadog-php-tracer_1.0.0-nightly_noarch.apk

Please deploy this to a development or staging environment, not production.

We once again await feedback, and once again, thanks for patience ;)

**Comment by negoziator** [comment] 2022-01-04 17:51
@krakjoe I will happily test the nightly build out.

Let me get back to you on what I experience.

**Comment by krakjoe** [comment] 2022-01-07 17:06
bump any update on the latest nightly build ?

/cc @negoziator @rodehoed

**Comment by krakjoe** [comment] 2022-02-02 03:33
Since we haven't had any feedback for a month, I'm closing this one.

If I'm wrong to do that, please open a new issue.

**Closed by krakjoe** 2022-02-02 03:33 UTC
Labels: 🐛 bug, question, sev-1, cat:app-crash
