### ISSUE TITLE
installation fine but port 8126 not listening

### ISSUE THREAD

**Issue by azhari7** [DataDog/dd-trace-php#582] opened 2019-09-19 08:07 UTC
hai i have  problem with the installation, im sure the configuration is right but when i try netstat -anp | grep 8126 nothing happen i use Centos 6.10, apache, php 7.0. and php-fpm

**Comment by labbati** [comment] 2019-09-19 08:44
Hi @azhari7, can you please deploy [`dd-doctor.php`](https://github.com/DataDog/dd-trace-php/blob/master/src/dd-doctor.php) to the server you used to test and access it at `my_server.com/dd-doctor.php`. It will tell you what's going on, starting from there we can help a little bit more.

**Comment by azhari7** [comment] 2019-09-19 09:44
this is result 
![phpdoctor](https://user-images.githubusercontent.com/13980646/65233133-8802a800-dafc-11e9-8f4d-f8e39ca8170c.png)

**Comment by labbati** [comment] 2019-09-19 16:04
Thanks for sharing, then the problem here is that we are not able to reach the agent. How is your infrastructure? Is the agent running locally in the same host as the php-fpm process or a different one?

**Comment by azhari7** [comment] 2019-09-19 22:38
Agent and php-fpm running in same host
In log jus say "listening to localhost:8126 and no data receive "

**Comment by labbati** [comment] 2019-09-20 08:33
@azhari7 can I ask you to run this command from the host and show me the output?

```
curl localhost:8126/v0.4/traces \
    -X POST \
    -H 'Content-Type: application/json' \
    -d '[[{"span_id":7888852067085145860,"trace_id":8410276558263903151,"parent_id":0,"name":"symfony.request","service":"some_service","type":"web","resource":"/","start":1568281716000000000,"duration":265471}]]'
```

This command will 'manually' try to send a trace to the agent using `curl`. Note that the trace won't appear in the UI as it is expired, yet looking at the output of the command can demonstrate that the agent connection works and the problem is on PHP side.

**Comment by azhari7** [comment] 2019-09-20 09:44
from curl above agent connection works well finally apm service appear. but just appear some_service that curl send 
![phpdoctor_1](https://user-images.githubusercontent.com/13980646/65317352-dfb91600-dbc5-11e9-86e1-fb4916a09e1c.png)

**Comment by labbati** [comment] 2019-09-20 11:58
@azhari7 I just noticed a thing from https://github.com/DataDog/dd-trace-php/issues/582#issuecomment-533054068.

I think you executed the script from the command line. Instead, it should be copied to the web root of your local/development/staging machine that you are testing and then accessed via a web browser at `http://<my_internal_development_server_host>/dd-doctor.php`.

The reason why I am asking is that php-fpm might have extra params et, e.g. through fastcgi_param, that alter the end result.

**Comment by azhari7** [comment] 2019-09-23 02:43
the result executing from web is same as i exec form cli
![phpdoctor_2](https://user-images.githubusercontent.com/13980646/65399389-87149380-dde6-11e9-8d40-72871558ee7e.png)

**Comment by labbati** [comment] 2019-10-17 09:25
@azhari7 just checking in. any progress on this issue? To sum up:

- php server and trace agent runs on same host (no docker)
- running command `curl localhost:8126/v0.4/traces .....` is able to send traces to the backend
- dd-doctor.php cannot send traces from that same host to that same host.

This is very strange. Do you set any special setting on php_curl? @SammyK @pawelchcki any idea why this can happen?

**Comment by labbati** [comment] 2019-10-17 09:25
(reopening as I closed by mistake)

**Comment by azhari7** [comment] 2019-10-18 02:57
this is the progress of the issues :
    -  php server and trace agent runs on same host (no docker)
    -  running command curl localhost:8126/v0.4/traces ..... is able to send traces to the backend
    -   dd-doctor.php able to send traces from that same host to that same host.
    -   but in the log trace-agent says No data receive
![phpdoctor_3](https://user-images.githubusercontent.com/13980646/67062530-bae89c00-f18d-11e9-90c1-3839f9a18ad9.png)

**Comment by labbati** [comment] 2019-11-04 08:47
Hi @azhari7, at this point the only thing that is possible is that automatic instrumentation is not triggered. We use `spl_autoload_register` as a hook to trigger automatic instrumentation, is there any chance your application is not registering any autoloader? E.g. if your application uses composer then it DOES register an autoloader, if your app is a super simple script with no autoloader then please read on.

In case your application is not registering any autoloader, I recommend you to set the two following envs (note: we are working to remove the need for them, removing the first will take some time, removing the second is part of the next sprint):

- `DD_TRACE_NO_AUTOLOADER=true`
- `DD_TRACE_URL_AS_RESOURCE_NAMES_ENABLED=true`

_Note_: version 0.34.0+ is required.

If this is not then please let me know so we can setup some more extensive debug session, if you are interested. Bringing in also @SammyK and @morrisonlevi if they have any suspect about where the problem might be.

**Comment by labbati** [comment] 2019-11-11 14:45
Hi @azhari7 did you have a chance to try what I suggested above :)

**Comment by morrisonlevi** [comment] 2020-01-14 16:40
@azhari7, just checking in with you again. Are you using a composer-based autoloader? If not, have you had a chance to try out Luca's suggestions?

**Comment by labbati** [comment] 2020-06-09 07:43
Closing this issue for now as it is stale. Please feel free to reopen it if you still observe the problem.

**Closed by labbati** 2020-06-09 07:43 UTC
