### ISSUE TITLE
dd-trace 0.40.0 causes `Cannot declare trait DDTrace\Log\LoggingTrait`

### ISSUE THREAD

**Issue by Majkl578** [DataDog/dd-trace-php#768] opened 2020-02-26 10:42 UTC
We're seeing errors during Datadog initialization apparently caused by some internal race conditions.

```
PHP Fatal error:  Cannot declare trait DDTrace\Log\LoggingTrait, because the name is already in use in /opt/datadog-php/dd-trace-sources/src/DDTrace/Log/LoggingTrait.php on line 5
Symfony\Component\ErrorHandler\Error\FatalError {#341
  -error: array:4 [
    "type" => 64
    "message" => "Cannot declare trait DDTrace\Log\LoggingTrait, because the name is already in use"
    "file" => "/opt/datadog-php/dd-trace-sources/src/DDTrace/Log/LoggingTrait.php"
    "line" => 5
  ]
  #message: "Compile Error: Cannot declare trait DDTrace\Log\LoggingTrait, because the name is already in use"
  #code: 0
  #file: "/opt/datadog-php/dd-trace-sources/src/DDTrace/Log/LoggingTrait.php"
  #line: 5
}
```

We're registering Symfony bundle in Symfony kernel from explicitly required `"datadog/dd-trace": "0.40.0" however we don't perform any other manual instrumentation - ddtrace is configured via environment variables only, tracer is enabled with `DD_TRACE_ENABLED: true`.

Looks like #672 which was alegedly fixed.

_We're on a Datadog Pro plan._

**Comment by labbati** [comment] 2020-02-26 11:34
Investigating this.

**Comment by labbati** [comment] 2020-02-26 11:38
In the meantime:

> "datadog/dd-trace": "0.40.0" however we don't perform any other manual instrumentation

If you are not performing any manual instrumentation you do not need to include it in composer. You only have to install the extension and everything is automatic.

Question: is the error above the only info you have? Any stack trace of where that is happening?

**Comment by labbati** [comment] 2020-02-26 11:38
Just to be clear, this is a bug and I am investigating this as a stability issue.

**Comment by labbati** [comment] 2020-02-26 12:29
@Majkl578 I am reading better your message

> We're registering Symfony bundle in Symfony kernel.

You mean that you are explicitly declaring the bundle in your kernel? Can you please share your symfony `.yml` where you are doing this? Because if you are doing it I guess we found the problem.

- this has never been required (we were doing it for you)
- it is not required now and it can actually conflict badly after [0.36.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.36.0). Which version of dd-trace-php you are updating from?
- This scenario is not tested, I can try to test if I can reproduce but in either case you should remove our bundle from the kernel.
- If this worked before it was incidental.

**Comment by Majkl578** [comment] 2020-02-26 14:34
> You mean that you are explicitly declaring the bundle in your kernel?

Yes, I'm registering it as a bundle in the kernel's `registerBundles()`:
```
new DDTrace\Integrations\Symfony\V4\SymfonyBundle()
```

That is by the way exactly what that class says in its phpDoc (just with wrong namespace):
```
/**
 * DataDog Symfony tracing bundle. Use by installing the dd-trace library:
 *
 * composer require datadog/dd-trace
 *
 * And then add the bundle in app/AppKernel.php:
 *
 *         $bundles = [
 *             // ...
 *             new DDTrace\Integrations\SymfonyBundle(),
 *             // ...
 *         ];
 */
class SymfonyBundle extends Bundle
```

Our `.yml` configuration files have no reference to the bundle itself, we're only registering necessary services so we can use them in the app (for spans etc.):
```yml
  DataDog\DogStatsd:
  DDTrace\Contracts\Tracer: '@DDTrace\Tracer'
  DDTrace\Encoder: '@DDTrace\Encoders\Json'
  DDTrace\Encoders\Json:
  DDTrace\NoopTracer:
  DDTrace\Tracer:
  DDTrace\Transport\Http:
```

> Which version of dd-trace-php you are updating from?

None, this app currently doesn't have dd-trace installed.
However we have another PHP app which works without issues with `datadog/dd-trace` in `composer.json` and dd-trace 0.40.0.


---

>  You only have to install the extension and everything is automatic.

I really dislike this approach but that's for a talk in another issue. :)

**Comment by labbati** [comment] 2020-02-27 09:37
@Majkl578 I am sorry for that comment, that is a deprecated class that we are about to remove soon and that comment is completely misleading. I am removing it here: #772 

@Majkl578 can you please remove our bundle from the bundles registration and confirm it works?

**Comment by Majkl578** [comment] 2020-02-27 12:12
Yep, removing the bundle registration seems make the issue disappear.

But is there any chance to be able to bootstrap ddtrace manually, without all this hidden dark magic? And to also avoid magically prepending an autoloader to load stuff from `/opt/datadog-php/dd-trace-sources/src/DDTrace/` instead of local `vendor/`?
It's really scaring me (us) off in an automated environment.

**Comment by labbati** [comment] 2020-02-27 14:31
@Majkl578 thanks for confirming that, and BTW I am sorry about the confusion, we just merged a PR https://github.com/DataDog/dd-trace-php/pull/772 to remove that obsolete docblock (I think it was there for <0.10 or so).

Talking about
>But is there any chance to be able to bootstrap ddtrace manually, without all this hidden dark magic?
Can I ask why? Please not that we are in the process of removing more and more things from the php layer so, in our path forward, the composer package will only be a shim, or a proxy if you like, to a lower level api which will exist in the extension.

**Comment by morrisonlevi** [comment] 2020-02-27 16:08
To clarify, you don't want any automated instrumentation. You want to configure exactly all the integrations that get loaded, presumably in some sort of `setup.php` or common configuration area. Is that correct?

**Comment by labbati** [comment] 2020-03-02 17:28
@Majkl578 I think we can close this issue [BUG] as it was a misuse of the Bundle, justify by wrong docs! I would ask you to open a different issue if you would propose for a different approach for us to bootstrap automatic instrumentation. That would be a feature request / improvement instead of a bug at that point.

**Closed** 2020-03-02 17:28 UTC
Labels: 🐛 bug
