### ISSUE TITLE
[BUG] Libexecinfo on alpine

### ISSUE THREAD

**Issue by sgerme** [DataDog/dd-trace-php#1844] opened 2023-01-09 13:47 UTC
### Bug description
Installing ddog tracer for php on php-8.2-alpine fails

### PHP version
8.2

### Tracer version
0.82

### OS info
alpine latest

### Diagnostics and configuration

```

Download Datadog version 0.82.0
wget https://github.com/DataDog/dd-trace-php/releases/download/0.82.0/datadog-php-tracer_0.82.0_x86_64.apk

fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
 ERROR: unable to select packages:
 libexecinfo (no such package):
 required by: world[libexecinfo]
 libexecinfo-dev (no such package)
 required by: world[libexecinfo-dev]
 ```
I had to remove it from our ci since it's breaking the containers creation.

**Comment by bwoebi** [comment] 2023-01-09 13:50
Duplicate of #1824 - it'll be fixed in the next release.

**Closed by bwoebi** 2023-01-09 13:50 UTC
Labels: 🐛 bug

**Comment by bwoebi** [comment] 2023-01-13 18:39
Hey @sgerme,

0.83.0 has been released now, removing the libexecinfo dependency.
