### ISSUE TITLE
[BUG] `php artisan` runs into segmentation fault on laravel 9 and php8.1.0, php 8.1.1 and php 8.1.2

### ISSUE THREAD

**Issue by christoph-kluge** [DataDog/dd-trace-php#1734] opened 2022-09-09 12:24 UTC
### Bug description

After debugging #1732 further I decided to split this.

Laravel 9 / Artisan is not supported.

What is strange and perhaps might be an indicator: bullseye with --enable-debug works 🤷‍♂️ 

### Docker Image: Debian Bullseye 

|docker image|os|laravel|status|
|---|---|---|---|
| php:8.1.2 | debian bullseye | 8 | ✅ |
| php:8.1.2 | debian bullseye | 9 | segmentation fault |
| php:8.1.2-debug (with --enable-debug) | debian bullseye | 9 | ✅ (why?) |

### Docker Image: Alpine

|docker|os|laravel|status|
|---|---|---|---|
| php:8.1.2-alpine | alpine | 8 | ✅ |
| php:8.1.2-alpine | alpine | 9 | segmentation fault |
| php:8.1.2-alpine-debug (with --enable-debug) | alpine | 9 | setup-datadog.php fails with missing `ddtrace-debug.so` |

### Tracer version

`0.78.0`

### OS info

Host-System executing docker

```
MacOS Monterey 12.5.1
Chip: Apple M1 Max
Darwin 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64
```

```
% docker --version
Docker version 20.10.17, build 100c701
```

#### Alpine + Laravel 8 / 9 

```
FROM php:8.1.2-alpine

RUN apk add libexecinfo-dev
RUN curl -LO https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php && php datadog-setup.php --php-bin=all

RUN apk add wget git unzip gdb
RUN wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet

RUN ./composer.phar create-project laravel/laravel:^8 example-laravel-8
RUN ./composer.phar create-project laravel/laravel:^9 example-laravel-9
```

#### Debian Bullseye + Laravel 8 / 9 

```
FROM php:8.1.2

RUN apt update
RUN curl -LO https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php && php datadog-setup.php --php-bin=all

RUN apt install -y wget git unzip gdb
RUN wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet

RUN ./composer.phar create-project laravel/laravel:^8 example-laravel-8
RUN ./composer.phar create-project laravel/laravel:^9 example-laravel-9
```

#### Debian Bullseye + Laravel 8 / 9 + `--enable-debug` - works?!

``` 
FROM christophkluge/php:8.1.2-debug

RUN apt update
RUN curl -LO https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php && php datadog-setup.php --php-bin=all

RUN apt install -y wget git unzip gdb
RUN wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet

# RUN ./composer.phar create-project laravel/laravel:^8 example-laravel-8
# RUN ./composer.phar create-project laravel/laravel:^9 example-laravel-9
```

**Comment by bwoebi** [comment] 2022-09-09 17:59
Hey @christoph-kluge,

we have recently fixed a segmentation fault (#1727) which possibly is related. Could you please verify whether the crash persists with 0.79.0?

Thanks!

**Comment by morrisonlevi** [comment] 2022-09-10 02:18
@bwoebi, I can reproduce a sigsegv during building the Dockerfile:

```
FROM php:8.1.2

RUN apt update
RUN curl -LO https://github.com/DataDog/dd-trace-php/releases/download/0.79.0/datadog-setup.php && php datadog-setup.php --php-bin=all

RUN apt install -y wget git unzip gdb
RUN wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet

RUN ./composer.phar create-project laravel/laravel:^9 example-laravel-9
```

Here are the last few lines:

```
#9 32.97 Generating optimized autoload files
#9 34.77 > Illuminate\Foundation\ComposerScripts::postAutoloadDump
#9 34.78 > @php artisan package:discover --ansi
#9 34.91 Segmentation fault
#9 34.91 Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 139
```

I'm on an Intel Mac in case that ends up mattering somehow.

**Comment by morrisonlevi** [comment] 2022-09-10 02:28
A possibly important finding: I did not crash on `php:8.1.10`. Of course, sometimes things just _subtly_ change and it hides the issue, rather than something being fixed.

**Comment by bwoebi** [comment] 2022-09-10 20:16
PHP 8.1.3 had a critical bugfix related to observing attributes. (https://github.com/php/php-src/commit/2f6a06ccb0ef78e6122bb9e67f9b8b1ad07776e1)

That's the only thing which stands out to me, and it's not really fixable, except by using a version newer than 8.1.2 I guess.

**Comment by christoph-kluge** [comment] 2022-09-15 05:37
Changing the php image to 8.1.3 fixed this issue. 

Perhaps it's worth adding some
version check inside datadog-setup.php and prevent installs if you run php 8.1 below 8.1.3.

**Comment by bwoebi** [comment] 2022-09-15 09:45
The problem is that most code on PHP 8.1.0-8.1.2 is fine, unless it's very new code.
Adding a check might break other clients setup, where it currently runs fine. There are no great solutions to that, I think.

**Comment by christoph-kluge** [comment] 2022-09-15 13:06
True. I totally forgot this fact. It only applys to laravel 9 + ddtrace and php 8.1.0 - 8.1.2.

My idea was how to prevent this for some other people. Anyway I've changed the title to me a bit more precise if some else searches for it. 

In my personal opinion this issue can be closed.

**Comment by krakjoe** [comment] 2022-10-14 11:57
Since @christoph-kluge is happy to close, and since we can't really think of any good solution (except using a version that includes the fix upstream), I'm closing this now.

It remains for reference, thanks for the report 👍

**Closed by krakjoe** 2022-10-14 11:57 UTC
Labels: 🐛 bug
