### ISSUE TITLE
Add support for RedisCluster

### ISSUE THREAD

**Issue by brunopadz** [DataDog/dd-trace-php#1016] opened 2020-09-11 14:16 UTC
### Bug description
I'm unable to get any trace or span information in requests that uses redis, the application uses Laravel 5.7.

I see that phpredis was supported recently, but I can't find a way to make it send the traces.

ENV VARs that are enabled in this environment:

```
DD_TRACE_CLI_ENABLED = true
DD_TRACE_DEBUG = 1
DD_TRACE_ENABLED = true
DD_TRACE_HTTP_CLIENT_SPLIT_BY_DOMAIN = true
DD_TRACE_PHPREDIS_ENABLED = true
```

Using dd-trace-php 0.48.1 and dd-agent 7.22.0

### PHP version
```
PHP 7.2.28 (cli) (built: Mar  3 2020 18:09:18) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.28, Copyright (c) 1999-2018, by Zend Technologies
    with ddtrace v0.48.1, Copyright Datadog, by Datadog
```

### Installed extensions
```
[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
ddtrace
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imagick
intl
json
libxml
mbstring
mcrypt
memcache
memcached
mongodb
mysqli
mysqlnd
OAuth
odbc
openssl
pcntl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
rdkafka
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
ssh2
standard
sysvmsg
sysvsem
sysvshm
tokenizer
uuid
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
ddtrace
```

### OS info
```
NAME="Amazon Linux AMI"
VERSION="2018.03"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
```

#### Output of phpinfo() (ddtrace >= 0.47.0)

![Screen Shot 2020-09-11 at 11 15 08](https://user-images.githubusercontent.com/1850071/92936222-38f60700-f420-11ea-9ef0-12679e8ffcca.png)

**Comment by morrisonlevi** [comment] 2020-09-11 14:32
Thank you for the report, and sorry you are having troubles. Aside from not seeing spans for phpredis, is everything else working like you expect? Is it crashing? You should update to 0.48.2 as there is a stability issue in 0.48.0-0.48.1 that can be triggered by both PhpRedis and Redis.

If it's not crashing let me know and I'll have an escalation engineer look at this when they are available.

**Comment by brunopadz** [comment] 2020-09-11 14:54
Hi @morrisonlevi, thanks for your quickly response.

Yeah, everything is working except the traces from redis. Just updated to 0.48.2 and no success, I still can't see the spans.

Oh, another info, I'm using phpredis 5.2.2.

**Comment by labbati** [comment] 2020-09-14 16:17
Hi @brunopadz, can you show us how you are using phpredis?

- Is it through Laravel's cache facades?
- Directly from your code? Can you provide an example?
- Also, are you using `Redis` or `RedisCluster`?

**Comment by brunopadz** [comment] 2020-09-14 17:11
Hey @labbati, 

We're using Cache Facades, Redis Facades and Repository.

Here's some examples directly from our code:

**Cache Facades**

```php
    public function download()
    {
        $downloadId = $this->getUniqueId();

        Cache::put(
            "index_based_on_$downloadId",
            $this->getTitle(),
            $this->getTtl()
        );

        Cache::put("status_based_on_$downloadId", 'in_queue', $this->getTtl());

        $this->dispatch($this->buildJob());

        return action(
            'GenericController@genericMethod',
            ['id' => $downloadId]
        );
    }
```

**Redis Facades**

```php
final protected function updateToken(string $token): void
{
    Redis::set('external_service__token', $token);
}

final protected function getToken(): ?string
{
    return Redis::get('external_service__token') ?? null;
}
```

**Repository**

```php
private function lock(): void
{
    try {
        $this->warn('[Command] Release locking');
        $this->repository->put('generic:command', $this->host, self::INTERVAL_IN_MINUTES);
    } catch (Exception $exception) {
        $this->error('[Command] Release locking fail');
        $this->error($exception->getMessage());
        $this->error($exception->getTraceAsString());
    }
}
```

We're using `Redis`. 

Thanks very much.  :)

cc: @vidalvasconcelos

**Comment by SammyK** [comment] 2020-09-14 22:46
Thanks for all the information @brunopadz! We have been working to replicate this issue on our end yet, but we haven't been able to replicate it yet.

In the support ticket it mentioned that there was custom instrumentation for MongoDB via OpenTracing.

0. Is that implemented [via the `opentracing/opentracing` library](https://docs.datadoghq.com/tracing/custom_instrumentation/php/?tab=tracingfunctioncalls#opentracing)?
0. If so, where is the bootstrapping code (`\OpenTracing\GlobalTracer::set($otTracer);`) called in the Laravel app?
0. Are there any other custom instrumentations?

**Comment by labbati** [comment] 2020-09-15 12:05
Thanks @brunopadz. Let me add a question to @SammyK points.
Would it be possible for you to share the cache configuration? If you use the standard Laravel 5.7 directory structure, I am referring to `config/cache.php`. If you prefer to share it privately please feel free to open a support ticket or using an existing one.

**Comment by brunopadz** [comment] 2020-09-15 13:36
Thanks @SammyK and @labbati :)

@vidalvasconcelos is going to answer the question @SammyK did.

In the meantime, here's the cache config:

```php
<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Default Cache Driver
    |--------------------------------------------------------------------------
    |
    | This option controls the default cache "driver" that will be used when
    | using the Caching library. Of course, you may use other drivers any
    | time you wish. This is the default when another is not specified.
    |
    | Supported: "file", "database", "apc", "memcached", "redis", "array"
    |
    */

    'default' => env('CACHE_DRIVER', 'array'),

    /*
    |--------------------------------------------------------------------------
    | Cache Key Prefix
    |--------------------------------------------------------------------------
    |
    | When utilizing a RAM based store such as APC or Memcached, there might
    | be other applications utilizing the same cache. So, we'll specify a
    | value to get prefixed to all our keys so we can avoid collisions.
    |
    */

    'prefix' => env('APP_NAME', 'laramongo'),

    /*
    |--------------------------------------------------------------------------
    | Cache Stores
    |--------------------------------------------------------------------------
    |
    | Here you may define all of the cache 'stores' for your application as
    | well as their drivers. You may even define multiple stores for the
    | same cache driver to group types of items stored in your caches.
    |
    */

    'stores' => [
        'apc' => [
            'driver' => 'apc',
        ],

        'array' => [
            'driver' => 'array',
        ],

        'database' => [
            'driver' => 'database',
            'table' => 'cache',
            'connection' => null,
        ],

        'file' => [
            'driver' => 'file',
            'path' => storage_path('framework/cache'),
        ],

        'memcached' => [
            'driver' => 'memcached',
            'servers' => [
                [
                    'host' => '127.0.0.1',
                    'port' => 11211,
                    'weight' => 100,
                ],
            ],
        ],

        'redis' => [
            'driver' => 'redis',
            'connection' => env('CACHE_CONNECTION', 'default'),
        ],
    ],

    'ignore_es_cache' => env('IGNORE_ES_CACHE', false),
];
```

**Comment by vidalvasconcelos** [comment] 2020-09-15 13:51
Hello everyone!
We also have another file that was extracted with the cluster configurations:
```php
<?php

$redisConfig = [
    'client' => env('CACHE_CLIENT', 'phpredis'),

    'session' => [
        'host' => env('REDIS_HOST_SESSION', 'redis'),
        'password' => env('REDIS_PASSWORD', null),
        'port' => env('REDIS_PORT_NUMBER', 6379),
        'database' => env('REDIS_DB_SESSION', 1),
        'timeout' => env('REDIS_CONNECTION_TIMEOUT', 5),
    ],
];

if (env('CLUSTER_FEATURE_TOGGLE')) {
    $redisConfig['clusters'] = [
        'default' => [
            [
                'host' => env('REDIS_HOST_DEFAULT', <default host>),
                'password' => env('REDIS_PASSWORD', null),
                'port' => env('REDIS_PORT', <default port>),
                'timeout' => env('REDIS_CONNECTION_TIMEOUT', ),
            ],
        ],

        'options' => [
            'cluster' => 'redis',
        ],
    ];

    return $redisConfig;
}

$redisConfig['default'] = [
    'host' => env('REDIS_HOST_DEFAULT', <default host>),
    'password' => env('REDIS_PASSWORD', null),
    'port' => env('REDIS_PORT_NUMBER', <default port>),
    'database' => env('REDIS_DB_DEFAULT', 0),
    'timeout' => env('REDIS_CONNECTION_TIMEOUT', 5),
];

return $redisConfig;

```

About the @SammyK question: 

We are using "custom instrumentation" through this helper `\DDTrace\trace_method`, declaring some classes as \MongoDB\Operation\BulkWrite, like this:

```php
\DDTrace\trace_method(
     \MongoDB\Operation\BulkWrite::class,
     'execute',
     function (\DDTrace\SpanData $span, array $args, $retval, $exception): bool {
         if (!$parent = \DDTrace\GlobalTracer::get()->getActiveSpan()) {
             return false;
         }

         $span->name = 'mongolid-operation-bulk-write-execute';
         $span->resource = 'BulkWrite.Execute';
         $span->service = $parent->getService();
         return true;
     }
 );
```

Theses files contain this declarations are loaded join the application autoload:

```markdown
./bootstrap
├── app.php
├── autoload.php
├── cache
│   ├── packages.php
│   └── services.php
└── tracing
    ├── autoload.php
    ├── mongodb.php
    └── mongolid.php
```

**Comment by labbati** [comment] 2020-09-15 14:53
Hi @vidalvasconcelos and thanks for the snippets! One thing that might explain the bug is `CLUSTER_FEATURE_TOGGLE`. Could you provide the value of this flag for the service not reporting phpredis spans?

**Comment by vidalvasconcelos** [comment] 2020-09-15 16:46
@labbati is true

**Comment by labbati** [comment] 2020-09-15 17:05
Thank you @vidalvasconcelos! Then the issue is that we support phpredis via `Redis` class, in this case you are using `RedisCluster`, which is determined by the above flag. Let us get back to you with an ETA for us to add support for it.

**Comment by vidalvasconcelos** [comment] 2020-09-15 17:08
Thank you @labbati, we really appreciate your help and support!

**Comment by labbati** [comment] 2020-09-16 16:13
All, I changing the card title to "Add support for RedisCluster" and moving from Bug to FeatureRequest

**Comment by labbati** [comment] 2021-02-04 19:38
👋  support for `RedisCluster` has been added in [0.55.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.55.0).

Closing this issue now. Let me know if anything is not working as expected and I will reopen it.

**Closed by labbati** 2021-02-04 19:38 UTC
Labels: feature-request, integrations
