### ISSUE TITLE
Leftovers after uninstalling

### ISSUE THREAD

**Issue by Abraham-Tourdex** [DataDog/dd-trace-php#408] opened 2019-04-17 00:39 UTC
I ran datadog for a little while and then uninstalled it, but every now and then I get errors like this:

    Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table '[db].[tb]' doesn't exist in /opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/PDO/PDOIntegration.php:118 Stack trace: #0 [internal function]: PDO->query('SELECT producti...') #1 /opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/PDO/PDOIntegration.php(118): call_user_func_array(Array, Array) #2 /var/www/html/iconcierge/app/dashboard/products.php(21): PDO->DDTrace\Integrations\PDO\{closure}('SELECT producti...') #3 {main} thrown in /opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/PDO/PDOIntegration.php on line 118

How do I remove this from my system entirely? I have already run `sudo apt-get --purge remove datadog-agent -y` (I'm on ubuntu)

thanks!

**Comment by labbati** [comment] 2019-04-17 09:12
Hi @Abraham-Tourdex, let me explain the two actors in the game so it will be clear where the problem is.

In order for Datadog to collect APM traces for your PHP application we need to actors:
1. the "php tracing client" (that you installed I guess following the instructions [here](https://docs-staging.datadoghq.com/priyanshi/distributed_tracing_default/tracing/languages/php/#install-the-extension)). It is a PHP extension that collects traces from the PHP runtime and sends them to the datadog agent.
2. the "datadog agent" (that you installed I guess following instructions [here](https://app.datadoghq.com/account/settings#agent/ubuntu)). It collects traces from the "php tracing client" and forwards them to our backend.

With `sudo apt-get --purge remove datadog-agent -y` you removed 2. but 1. is still installed in your system.

In order to completely remove the php tracing client please:
- Remove file `/usr/local/etc/php/conf.d/98-ddtrace.ini` <-- this may vary on different systems but you can find the exact location running `php --ini`
- Remove folder `/opt/datadog-php`

A couple of notes:
- Even if you see our namespace in the exception, I guess that the missing table is the real error, so you don't have the error because of our tracer (I hope). We have plans to make sure our namespace doesn't appear in the stack trace unless appropriate, but we had to prioritize other tasks first
- We will add to our docs a section showing the proper way to uninstall our php tracing client from your system.

Thanks for taking the time to open this issue. I am closing it as my answer should address your question.

**Closed by labbati** 2019-04-17 09:12 UTC
