### ISSUE TITLE
Hangs/Doesn't execute `dd_trace`

### ISSUE THREAD

**Issue by magicalbanana** [DataDog/dd-trace-php#369] opened 2019-03-18 20:24 UTC
`dd_trace` hangs when I use it. There's no output or error. Just blocks forever. Any ideas why?

Update: Further debugging has shown me that `dd_trace` doesn't execute. No error whatsoever. 

```
if (extension_enabled('ddtrace')) {
  dd_trace('test', func() {
    die();
  });
}

dd_trace('test', func() {
  die();
});
```

@labbati sorry to tag you. But this has been an issue with us for quite sometime now.

**Comment by pawelchcki** [comment] 2019-03-20 12:40
Thanks for report @magicalbanana! This is indeed very strange behavior and I must say we haven't encountered it so far, and I couldn't reproduce it locally either. 
Would it be possible for you to provide a backtrace of hanging script (using gdb):
- run `gdb --args php offending_script.php`
- then once the scripts hangs press "ctrl+c"
- in gdb prompt type "backtrace" and press enter
That output is C level stacktrace that would be very useful in debugging this issue.

It would also greatly help if you could share some details about the setup you've encountered this problem in. I.e. OS/Distribution (or docker image name), installed extensions (output of `php -m`) and overall php config (output of `php -`). Thanks!

**Comment by labbati** [comment] 2019-03-27 18:31
Hi 👋! I was looking into this I may need some guidance here. So I guess the one above is pseudo-code? Is something like this still hang in your case?

```
<?php

if (extension_loaded('ddtrace')) {
    dd_trace('test', function () {
        die();
    });
}

dd_trace('test', function () {
    die();
});
```

Note though, that this code will not send traces but at least it should not hang.

I may be missing something though!

**Comment by labbati** [comment] 2019-08-19 10:46
Hi @magicalbanana this issue has been stale for a while, did you have a chance to look into our latest couple of messages? Also, are you testing this in a Docker environment, if yes and if you can provide us your docker file then we will be happy to debug ourself.

Sorry again about the issue you had.

**Comment by magicalbanana** [comment] 2019-08-19 13:43
@labbati I can't remember how I solved this but I think I ended up not using `dd_trace` but the package itself directly.

**Comment by labbati** [comment] 2019-08-19 14:49
Thanks for the heads up. I am closing this issue for now then. If more details comes to your mind that we can iterate over please feel free to re-open it. Thank you for you time.

**Closed by labbati** 2019-08-19 14:49 UTC
Labels: c-extension
