### ISSUE TITLE
[BUG] Segmentation faults for requests from Datadog Synthetics

### ISSUE THREAD

**Issue by ctrlrsf** [DataDog/dd-trace-php#1070] opened 2020-11-02 16:10 UTC
### Bug description
Some of our Datadog Synthetics tests have been failing due to Apache/PHP seg faulting. It seems related to the x-datadog-origin header that Datadog Synthetics tests add to our automated tests. When we drop this header at Apache, there's no crash and we get expected response.

### PHP version
```
PHP 7.2.34-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct  6 2020 12:01:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.34-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with ddtrace v0.48.3, Copyright Datadog, by Datadog
```

### Installed extensions
```
[PHP Modules]
apc
apcu
calendar
Core
ctype
curl
date
ddtrace
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imagick
intl
json
libxml
mbstring
mcrypt
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
ssh2
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
ddtrace
```

### OS info
```
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

#### Output of phpinfo() (ddtrace >= 0.47.0)
```
{"date":"2020-11-02T16:00:55Z","os_name":"Linux public.xyz 4.4.0-1114-aws #127-Ubuntu SMP Fri Sep 4 08:41:12 UTC 2020 x86_64","os_version":"4.4.0-1114-aws","version":"0.48.3","lang":"php","lang_version":"7.2.17","env":null,"enabled":true,"service":null,"enabled_cli":false,"agent_url":"http://localhost:8126","debug":false,"analytics_enabled":true,"sample_rate":1.000000,"sampling_rules":null,"tags":null,"service_mapping":null,"distributed_tracing_enabled":true,"priority_sampling_enabled":true,"dd_version":null,"architecture":"x86_64","sapi":"apache2handler","ddtrace.request_init_hook":"/opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php","open_basedir_configured":false,"uri_fragment_regex":null,"uri_mapping_incoming":null,"uri_mapping_outgoing":null,"auto_flush_enabled":false,"generate_root_span":true,"http_client_split_by_domain":false,"measure_compile_time":true,"report_hostname_on_root_span":false,"traced_internal_functions":null,"auto_prepend_file_configured":false,"integrations_disabled":null,"enabled_from_env":true,"opcache.file_cache":null,"DD_SERVICE_NAME":"'DD_SERVICE_NAME=public' is deprecated, use DD_SERVICE instead."}
--

```

**Comment by labbati** [comment] 2020-11-02 17:37
Hi @ctrlrsf, sorry for the crash. I wanted to let you know that we were able to recreate putting our sample application under some heavy load and introducing the synthetic origin header. It happens rarely (not all the requests) but we have core dumps to investigate. We will get back to you asap with a built for you to test out, if that works for you.

**Comment by ctrlrsf** [comment] 2020-11-02 21:10
Thanks @labbati. Yeah, that's what we noticed as well. Several requests affected randomly. Couldn't reproduce 100%, but enough to show up in our synthetics dashboard as failures consistently.

**Comment by labbati** [comment] 2020-11-09 13:33
Hi @ctrlrsf I wanted to provide an update on this issue. We have found the root cause and we are testing a fix. If it passes our memory checks and we are not able to recreate the issue under heavy load in our testing environment, we will release a patch very soon.

**Comment by ctrlrsf** [comment] 2020-11-09 17:29
Thank you for the update. We have a temporary workaround for now (dropping the header) but look forward to your fix.

**Comment by ralphiech** [comment] 2020-12-10 13:33
Any update here @labbati? we are struggling with the issue as well and had to roll back..

**Comment by labbati** [comment] 2020-12-10 15:01
Hi @ralphiech and @ctrlrsf. We have a custom build for you to try in your testing environment to confirm it solves your problem. If you confirm then we can release pretty soon.

- [tar.gz](https://293128-119990860-gh.circle-artifacts.com/0/datadog-php-tracer-1.0.0-nightly.x86_64.tar.gz)
- [deb](https://293128-119990860-gh.circle-artifacts.com/0/datadog-php-tracer_1.0.0-nightly_amd64.deb)
- [rpm](https://293128-119990860-gh.circle-artifacts.com/0/datadog-php-tracer-1.0.0_nightly-1.x86_64.rpm)
- [apk](https://293128-119990860-gh.circle-artifacts.com/0/datadog-php-tracer_1.0.0-nightly_noarch.apk)

**Comment by ralphiech** [comment] 2020-12-11 09:38
Hi @labbati thanks for the quick response. I am not sure if and how quickly I can do this testing, especially after I lost time on the upgrade due to the issue already. Any reason you are not releasing it, are you afraid of new issues? I would much rather wait for the release and test it then, that way I would not need to go through the testing exercise twice if that makes sense?

**Comment by ralphiech** [comment] 2020-12-15 13:41
Hey @labbati am just writing a regression test. Could you let me know which exact header (combination) is triggering a different execution path in the extension and causing the segfault?

**Comment by labbati** [comment] 2020-12-23 09:39
Hi @ralphiech I had totally missed this message. Here is a `curl` invocation that, repeated a few times (no longer than 10 typically), will recreate the issue.

```
 curl -v -H 'x-datadog-origin: some-origin' -H 'x-datadog-trace-id: 123' -H 'x-datadog-parent-id: 456' -H 'x-datadog-priority-sampling: 1' <host>:<port>
```

**Comment by ralphiech** [comment] 2020-12-23 10:02
Awesome, this is gold thanks @labbati. Am also very glad to see that the user-agent is not part of the equation here as we need it for other identification purposes in our integration tests.

I just compared with how I simulate it so far::

```
  simulateDatadogSyntheticsTest(event) {
    event.requestOptions.headers["sec-datadog"] =
      "Request sent by a Datadog Synthetics API Test (https://docs.datadoghq.com/synthetics/) - test_id: 8051|8dfd7f10-bc72-4fff-879d-181fbc72f464";
    event.requestOptions.headers["x-datadog-sampling-priority"] = "1";
    event.requestOptions.headers["x-datadog-origin"] = "synthetics";
    event.requestOptions.headers["x-datadog-parent-id"] = "0";
  }
 ```
 
 I took 'my version' from the test run in the datadog admin interface and tried to be as close to reality as possible w/a setting the `user-agent`. Interestingly you spell the sampling-priority different and you are also setting the `x-datadog-trace-id` is my version 'wrong' and should i adapt to yours?

**Comment by labbati** [comment] 2020-12-23 10:35
Hi @ralphiech,

> user-agent is not part of the equation

I confirm it is not part of the equation. The combination of `x-datadog-origin`, `x-datadog-trace-id` and `x-datadog-parent-id` are. We [stop extracting the context](https://github.com/DataDog/dd-trace-php/blob/73126655cf3660eac412809596cfd3d3fd29bbc4/src/DDTrace/Propagators/TextMap.php#L71-L72) (hence the problematic origin) if either trace id and parent id are not valid integers.

> Interestingly you spell the sampling-priority different and you are also setting the x-datadog-trace-id is my version 'wrong' and should i adapt to yours?

Your version is correct. I fixed my snippet. Sampling priority does not impact this specific issue, though. Thank you for flagging that.

**Comment by SammyK** [comment] 2020-12-30 21:36
@ctrlrsf This issue has been fixed in the [latest release](https://github.com/DataDog/dd-trace-php/releases/tag/0.53.0). Thanks for the report! /cc @ralphiech

**Closed by SammyK** 2020-12-30 21:36 UTC
Labels: 🐛 bug

**Comment by ralphiech** [comment] 2020-12-31 12:10
Thanks for the fix and headsup @labbati and @SammyK
