### ISSUE TITLE
When installed dd-trace-php my app not working

### ISSUE THREAD

**Issue by mehul-saleshandy** [DataDog/dd-trace-php#334] opened 2019-02-28 06:43 UTC
I was installed the "datadog-php-tracer_0.14.1-beta_amd64.deb" on my server and after installed my application return 500 error. Below is the things which I have configured or my server related information:
I am using Ubuntu, NGINX and php-fpm 7.0.
I have installed datadog agent v6.

For FPM I have set below configuration:
1) Installed : "datadog-php-tracer_0.14.1-beta_amd64.deb"
2) NGINX config: fastcgi_param DD_TRACE_DEBUG true;
3) Set ddtrace.log_backtrace=1 in file /etc/php/7.0/cli/conf.d/98-ddtrace.ini.
4) In Agent datadog.yaml: 
    apm_config:
       enabled: true

When I am checking my php-fpm log file, it shows the error about "Slim\PDO\Statement\StatementContainer->execute()". But when I disabled the Datadog Agent or APM trace then my application working normally well. In short when I am enable ddtrace my app not working and return 500 error.

Can you please look in it and let me know how can resolved the issue and APM work well with my app.

Also here attached my php error log file:
[php-fpm-log.txt](https://github.com/DataDog/dd-trace-php/files/2913683/php-fpm-log.txt)

**Comment by labbati** [comment] 2019-02-28 12:25
Hi @mehul-saleshandy, thanks for reporting this! We had a similar report from one of our customers. In his case the error disappeared if he set `DD_TRACE_DEBUG=false`. We are working to reproduce locally. Would it be possible for you to test the same app with `DD_TRACE_DEBUG=false
2\. fastcgi_param DD_TRACE_DEBUG false`?

**Comment by mehul-saleshandy** [comment] 2019-02-28 12:35
@labbati Thanks for your reply.
I just checked the set "fastcgi_param DD_TRACE_DEBUG false". But still my app not working. when disabled the ddtrace then my app working properly.

Below is log when I set the DD_TRACE_DEBUG=false.
```
[28-Feb-2019 12:29:53 UTC] Slim Application Error:
Type: Error
Message: Call to protected Slim\PDO\Statement::__construct() from context 'Slim\PDO\Statement\StatementContainer'
File: /var/www/html/api.mydomain.com/vendor/slim/pdo/src/PDO/Statement/StatementContainer.php
Line: 430
Trace: #0 /var/www/html/api.mydomain.com/vendor/slim/pdo/src/PDO/Statement/SelectStatement.php(411): Slim\PDO\Statement\StatementContainer->execute()
#1 /var/www/html/api.mydomain.com/src/Models/AppModel.php(352): Slim\PDO\Statement\SelectStatement->execute()
#2 /var/www/html/api.mydomain.com/src/middleware.php(144): App\Models\AppModel->fetch(Array)
#3 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#4 /var/www/html/api.mydomain.com/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Closure), Array)
#5 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#6 /var/www/html/api.mydomain.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#7 /var/www/html/api.mydomain.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /var/www/html/api.mydomain.com/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /var/www/html/api.mydomain.com/vendor/slim/slim/Slim/App.php(314): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 /var/www/html/api.mydomain.com/api/api.php(66): Slim\App->run()
#11 {main}
View in rendered output by enabling the "displayErrorDetails" setting.
```

**Comment by labbati** [comment] 2019-02-28 12:56
Ah now this is much more clear, thanks for sharing. This is known problem that we are currently and actively working on. As I cannot commit to that, the fix will be probably come out with the next release.

At an higher level, the cause an issue we have a in some specific cases while invoking private/protected methods and `parent::*` invocations.

In the meantime, if you are still interested in testing/using the other integrations, the only thing I can recommend is to disable the pdo integration: `fastcgi_param DD_INTEGRATIONS_DISABLED pdo`.

Again, the fix to this is currently in development and will be released very soon.

**Comment by okanozdemir** [comment] 2019-02-28 13:34
Hello, I have a similar issue and `fastcgi_param DD_TRACE_DEBUG false` not work on me too.

I'm using **PHP-FPM 7.1, Nginx 1.10.3, DataDog Agent 6.5.2**. I set `ddtrace.log_backtrace=1` in **ddtrace.ini** but **php-fpm.log / nginx-error.log / trace-agent.log** not log any error.

I also tried `fastcgi_param DD_INTEGRATIONS_DISABLED pdo` option but app still returns 500 error.

When stop datadog-agent or datadog-agent-trace error persists. Only if I commented `;extension=/opt/datadog-php/extensions/ddtrace-20160303.so` line and restart the PHP-FPM app works normally but tracing not work obviously.

**Comment by mehul-saleshandy** [comment] 2019-02-28 13:35
@labbati Thanks!
As I check disabled PDO so now tracing working for web.request.
I am waiting for new release, so PDO work there. Hope it will very soon.
Thanks for your great help!

**Comment by labbati** [comment] 2019-02-28 13:40
Hi @okanozdemir, would you be able to start from all integrations disabled `
fastcgi_param DD_INTEGRATIONS_DISABLED curl,elasticsearch,eloquent,guzzle,laravel,memcached,mongo,mysqli,pdo,predis,symfony,zendframework` and re-enabling (aka removing fromt he list above) one by one see which one is causing teh 500?

**Comment by SammyK** [comment] 2019-05-01 19:25
Hey @mehul-saleshandy & @okanozdemir! I've been trying to replicate your issue on my end and I wanted to confirm with you; are you [using `slim/pdo`](https://packagist.org/packages/slim/pdo) to connect to the database? :)

**Comment by mehul-saleshandy** [comment] 2019-05-02 04:40
Hi @SammyK, Yes I am using slim/pdo.

**Comment by labbati** [comment] 2019-06-12 15:42
@mehul-saleshandy it seems we are not able to reproduce this after [0.21.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.21.0). Can you confirm you were using a previous version?

**Comment by okanozdemir** [comment] 2019-06-19 08:50
My problem does not continue with latest version.

**Comment by mehul-saleshandy** [comment] 2019-06-19 09:20
@labbati I will check with latest version.

**Comment by morrisonlevi** [comment] 2019-10-02 18:32
Version [0.31.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.31.0) was released yesterday. In this update the PDO integration was sandboxed, so in most error situations it should not crash your app anymore, though that span will probably not show up. Let us know if your error persists after upgrading and removing the flag to disable PDO.

**Comment by satender1987** [comment] 2019-10-07 10:11
How can I configure DDTrace with slim? I have doubt either I should use .so file or I shouid use the composer install which is again written in php

**Comment by SammyK** [comment] 2020-01-08 19:04
@mehul-saleshandy I'm closing this issue, but feel free to re-open if upgrading to the latest version of the tracer does not resolve the issue. :)

@imsatender The PHP tracer currently supports [Slim v3](https://docs.datadoghq.com/tracing/setup/php/#web-framework-compatibility). You don't need to install the tracer with Composer. You just have to [install the extension](https://docs.datadoghq.com/tracing/setup/php/#install-the-extension) and Slim v3 should be instrumented automatically. :)

**Closed by SammyK** 2020-01-08 19:04 UTC
Labels: 🐛 bug
