### ISSUE TITLE
Installing on Alpine 3.5 fails to enable extension

### ISSUE THREAD

**Issue by carflo** [DataDog/dd-trace-php#381] opened 2019-03-25 23:42 UTC
To reproduce run `docker build` with the following Dockerfile:

```
FROM alpine:3.5

RUN apk --no-cache add \
        bash curl php5 libc6-compat \
        && ln -s /etc/php5 /etc/php

ENV DDTRACE_VERSION=0.16.1

RUN cd $(mktemp -d) \
    && curl -Lo datadog-php-tracer.apk https://github.com/DataDog/dd-trace-php/releases/download/${DDTRACE_VERSION}/datadog-php-tracer_${DDTRACE_VERSION}_noarch.apk \
    && apk add datadog-php-tracer.apk --allow-untrusted \
    && rm datadog-php-tracer.apk
```
Error: 
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/datadog-php/extensions/ddtrace-20131106.so' - Error relocating /opt/datadog-php/extensions/ddtrace-20131106.so: backtrace: symbol not found in Unknown on line 0
```

**Comment by labbati** [comment] 2019-03-27 09:52
Hi @carflo thanks for reporting this issue. We commit to look into this ASAP! In the meantime if you find any workaround/fix please post it here!

**Comment by labbati** [comment] 2019-03-28 11:19
![](https://github.trello.services/images/mini-trello-icon.png) [Installing on Alpine 3.5 fails to enable extension](https://trello.com/c/VVALOEd5/1620-installing-on-alpine-35-fails-to-enable-extension)

**Comment by tatianajiselle** [comment] 2019-08-06 22:03
Hey there -- were experiencing the same issue here

```NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'ddtrace.so' (tried: /usr/lib/php7/modules/ddtrace.so (Error relocating /usr/lib/php7/modules/ddtrace.so: _zval_ptr_dtor: symbol not found), /usr/lib/php7/modules/ddtrace.so.so (Error loading shared library /usr/lib/php7/modules/ddtrace.so.so: No such file or directory)) in Unknown on line 0```

**Comment by SammyK** [comment] 2019-08-06 23:08
Hey @tatianajiselle! Did you install the tracer via [the **.apk** package](https://github.com/DataDog/dd-trace-php/releases/download/0.27.2/datadog-php-tracer_0.27.2_noarch.apk)?

```bash
$ apk add datadog-php-tracer_0.27.2_noarch.apk --allow-untrusted
```

Installing it via a package should link everything properly. :)

**Comment by tatianajiselle** [comment] 2019-08-14 00:44
havent had a moment! will try this and get back to you thanks sammy...

**Comment by morrisonlevi** [comment] 2019-12-12 01:02
Have the recent `.apk` packages been working for you on Alpine Linux, @tatianajiselle and @carflo?

**Comment by jason-linthwaite** [comment] 2020-01-17 10:48
My installation has just stopped working after updating to not use a previously cached version in my docker.
anyone else getting issues?

I'm using

FROM php:7.2-fpm-alpine

and

RUN curl -L -s https://github.com/DataDog/dd-trace-php/releases/download/0.36.0/datadog-php-tracer_0.36.0_noarch.apk --output datadog-php-tracer.apk
RUN apk add datadog-php-tracer.apk --allow-untrusted

Just started returning error 

### Failed enabling ddtrace extension
###
### The extension has been installed but couldn't be enabled

**Comment by morrisonlevi** [comment] 2020-03-16 15:06
As an update, the PR from February fixes builds from source on Alpine. There is still a packaging issue which can be tracked in this PR #774.

**Comment by labbati** [comment] 2020-09-28 10:36
Answering to this own issue very late.

@jason-linthwaite 
We need more info as this is working for me. Can you provide a sample Dockerfile if you still experience the issue?

```
FROM php:7.2-fpm-alpine

RUN apk --no-cache add \
        bash curl libc6-compat libexecinfo

ENV DDTRACE_VERSION=0.36.0
ENV DDTRACE_DOWNLOAD_URL https://github.com/DataDog/dd-trace-php/releases/download/${DDTRACE_VERSION}/datadog-php-tracer_${DDTRACE_VERSION}_noarch.apk

RUN curl -Lo datadog-php-tracer.apk ${DDTRACE_DOWNLOAD_URL} \
    && apk add datadog-php-tracer.apk --allow-untrusted

CMD bash
```

@carflo 

I am still looking into this.

**Comment by labbati** [comment] 2020-10-02 16:46
@carflo I have a development build that I'd ask you to try, if you have a minute. Please note that this is not production read and it only supports 5.6.

I slightly modified version of your `Dockerfile` to include this development build.

```
FROM alpine:3.5

RUN apk --no-cache add bash curl php5 libexecinfo

RUN cd $(mktemp -d) \
    && curl -Lo datadog-php-tracer.apk https://238577-119990860-gh.circle-artifacts.com/0/datadog-php-tracer_1.0.0-nightly_noarch.apk \
    && apk add datadog-php-tracer.apk --allow-untrusted \
    && rm datadog-php-tracer.apk
```

Of course I tested in the `Dockerfile` above, but is this was a snippet of a larger `Dockerfile` I'd ask you to test in that one and confirm it works with no problems for you.

**Comment by carflo** [comment] 2020-10-05 17:47
@labbati I updated my `Dockerfile` with your changes and it worked! 

```
ddtrace
### Extension enabled successfully
```

**Comment by labbati** [comment] 2020-10-06 08:28
This is a very good news. We are currently actively working on #774 that will not be included in the next release (as it targets the next few days) but surely the following one.

**Comment by labbati** [comment] 2020-10-15 14:18
Change has been merged and it will be included in 0.50.0

**Closed** 2021-08-20 19:14 UTC
Labels: 🐛 bug, c-extension, cat:installation

**Comment by jetstudio-io** [comment] 2022-03-10 14:03
we got the error while enabling the extension on Alpine 3.15.
The Dockerfile:
```
FROM composer:2.0 AS composer
FROM php:8.0.14-fpm-alpine3.15
COPY --from=composer /usr/bin/composer /usr/bin/composer
ENV DDTRACE_VERSION=0.70.1
ENV DDTRACE_DOWNLOAD_URL https://github.com/DataDog/dd-trace-php/releases/download/${DDTRACE_VERSION}/datadog-php-tracer_${DDTRACE_VERSION}_noarch.apk
RUN curl -Lo datadog-php-tracer.apk ${DDTRACE_DOWNLOAD_URL} \
    && apk add datadog-php-tracer.apk --allow-untrusted
```

The error output in php cli
```
/app # php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/datadog-php/extensions/ddtrace-20200930-alpine.so' (tried: /opt/datadog-php/extensions/ddtrace-20200930-alpine.so (Error relocating /opt/datadog-php/extensions/ddtrace-20200930-alpine.so: unsupported relocation type 8), /usr/local/lib/php/extensions/no-debug-non-zts-20200930//opt/datadog-php/extensions/ddtrace-20200930-alpine.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20200930//opt/datadog-php/extensions/ddtrace-20200930-alpine.so.so: No such file or directory)) in Unknown on line 0
PHP 8.0.14 (cli) (built: Dec 18 2021 03:02:20) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.14, Copyright (c), by Zend Technologies
```

**Comment by labbati** [comment] 2022-03-10 14:55
The files you provided worked for me on x86. I think the problem is that you are using arm64.
In this case you can find more info in #1252 and #1145.
We are PoC-ing arm builds probably next week.

**Comment by TomKeur** [comment] 2022-08-24 14:29
Since we're also running Datadog inside an Alpine container:
How can we enable the Profiler?

With the PHP script, it's an additional CLI flag: "--enable-profiling", but since we're installing the .apk file, I'm sure this will not work.

Also any idea when the PHP installation will work? Because we need to update the APM version on every release.
For example this is not working:
https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-php-tracer_latest_aarch64.apk
https://github.com/DataDog/dd-trace-php/releases/download/latest/datadog-php-tracer_latest_aarch64.apk

**Comment by morrisonlevi** [comment] 2022-08-24 15:33
:wave: The datadog-setup.php script also works on Alpine. If you want profiling or appsec, then you need to use the datadog-setup.php script instead of the .apk. Notably, you can use the the GitHub latest shortcut with it: https://github.com/DataDog/dd-trace-php/releases/download/latest/datadog-setup.php. Of course, you need to understand the gotchas there (you'll update automatically even if there breaking or other important changes to be aware of).

**Comment by pedrosalpr** [comment] 2022-08-26 20:02
Hello, since it was updated to version 0.78.0, and as it doesn't have the `_noarch.apk` version, the builds are failing.

The build script in the dockerfile using the alpine image:

```
## Install latest version of datadog tracer
RUN curl -s https://api.github.com/repos/DataDog/dd-trace-php/releases/latest | grep "browser_download_url.*apk" | cut -d / -f 8,8 > DATADOG_VERSION \
    && wget https://github.com/DataDog/dd-trace-php/releases/download/$(cat DATADOG_VERSION)/datadog-php-tracer_$(cat DATADOG_VERSION)_noarch.apk \
    && apk add --no-cache --allow-untrusted datadog-php-tracer_$(cat DATADOG_VERSION)_noarch.apk \
    && rm datadog-php-tracer_$(cat DATADOG_VERSION)_noarch.apk
```

And result:

![Captura de Tela 2022-08-26 às 17 01 05](https://user-images.githubusercontent.com/5918761/186982447-a90c969b-8fe7-45cf-b8e7-0039d3d6bf59.png)

**Comment by thiagoinnfo** [comment] 2022-09-09 11:54
Hello @bwoebi,
I have the same problem described above, I tried to change noarch by $(uname -m), but it did not work.
Seems to be a problem with $(cat DATADOG_VERSION).

**Comment by bwoebi** [comment] 2022-09-13 10:17
```
FROM php:8.1-fpm-alpine3.15

## Install latest version of datadog tracer
RUN curl -s https://api.github.com/repos/DataDog/dd-trace-php/releases/latest | grep "browser_download_url.*apk" | head -1 | cut -d / -f 8,8 > DATADOG_VERSION \
    &&  wget https://github.com/DataDog/dd-trace-php/releases/download/$(cat DATADOG_VERSION)/datadog-php-tracer_$(cat DATADOG_VERSION)_$(uname -m).apk \
    && apk add --no-cache --allow-untrusted datadog-php-tracer_$(cat DATADOG_VERSION)_$(uname -m).apk \
    && rm datadog-php-tracer_$(cat DATADOG_VERSION)_$(uname -m).apk
```

This works for me.

**Comment by thiagoinnfo** [comment] 2022-09-13 12:14
@bwoebi 
It worked for me too. thanks
