### ISSUE TITLE
[BUG] Segmentation Fault

### ISSUE THREAD

**Issue by alecavallo** [DataDog/dd-trace-php#1012] opened 2020-09-10 12:34 UTC
**Describe the bug**
I have configured a site in CakePHP 2.10.19 in a docker fleet where one container runs an Nginx to serve static content and the other container runs a php-fpm using the image based on [php:7.3.12-fpm-alpine3.10](https://hub.docker.com/_/php?tab=tags&page=1&name=7.3.12-fpm-alpine3.10) 
[Dockerfile.txt](https://github.com/DataDog/dd-trace-php/files/5201538/Dockerfile.txt)

The PHP application connects to MySQL, MongoDB, and Redis to get data and cache it.
After I installed ddtrace for PHP it started to show 502 errors randomly. When I check the logs in PHP FPM container it shows a message like this:
`[10-Sep-2020 11:43:17] WARNING: [pool www] child 7 exited on signal 11 (SIGSEGV - core dumped) after 391.376478 seconds from start`
 Which disappears when I uninstall ddtrace.
I tried to locate where the Segmentation Fault occurs but it happens in different parts of the code each time the error is reproduced.

Also, I enabled the trace support in Xdebug and could obtain the following:
[trace.txt](https://github.com/DataDog/dd-trace-php/files/5201585/trace.txt)

Note the trace is not finished because it was interrupted by the Segmentation Fault.

Let me know if you need more data

**PHP Info**
- Php version:
`PHP 7.3.12 (cli) (built: Nov 22 2019 11:50:51) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.9.6, Copyright (c) 2002-2020, by Derick Rethans
    with ddtrace v0.48.0, Copyright Datadog, by Datadog
`
- Php modules: 
`[PHP Modules]
apcu
Core
ctype
curl
date
ddtrace
dom
fileinfo
filter
ftp
gd
hash
iconv
json
libxml
mbstring
mongodb
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
tokenizer
xdebug
xml
xmlreader
xmlrpc
xmlwriter
zip
zlib

[Zend Modules]
Xdebug
ddtrace
`

**OS Info**
- OS version (docker image):
`NAME="Alpine Linux"
VERSION_ID=3.10.3
PRETTY_NAME="Alpine Linux v3.10"
`

**Output of dd-doctor**
(Have into consideration it was run in a container in a local environment, not in production, that's why it's not able to connect to the agent)
`DataDog trace extension verification

- PHP version and SAPI                               [7.3.12 - fpm-fcgi]
- ddtrace extension installed                        [OK]
- ddtrace version (installed)                        [0.48.1]
- ddtrace version (const)                            [0.48.1]
- ddtrace version (userland)                         [0.48.1]
- ddtrace versions in sync                           [OK]
- dd_trace() function available                      [OK]
- dd_trace_env_config() function available           [OK]
- ddtrace.request_init_hook set                      [OK]
- ddtrace.request_init_hook reachable                [OK]
- ddtrace.request_init_hook has run                  [OK]
- 'open_basedir' allows access to '/proc/self/'      [OK]
- IntegrationsLoader exists                          [OK]
- Integrations loaded                                [OK]
- DDTrace\Tracer class exists                        [OK]
- Background sender is enabled?                      [NO]
  > You can enable the background sender via
    DD_TRACE_BETA_SEND_TRACES_VIA_THREAD=true
- Opcache installed:                                 [NO]
- Configured Agent host                              [localhost]
- Configured Agent port                              [8126]
- Agent can receive traces                           [FAIL]
Curl verbose output: 

*   Trying 127.0.0.1:8126...
* TCP_NODELAY set
* connect to 127.0.0.1 port 8126 failed: Connection refused
*   Trying ::1:8126...
* TCP_NODELAY set
* Immediate connect fail for ::1: Address not available
*   Trying ::1:8126...
* TCP_NODELAY set
* Immediate connect fail for ::1: Address not available
* Failed to connect to localhost port 8126: Connection refused
* Closing connection 0`

**Comment by labbati** [comment] 2020-09-10 12:44
Hi @alecavallo. Thanks for the report. I am looking into it right now trying to recreate using your provided docker file.
Thanks for all the details.
If I will not be able to recreate, I will ask you to open a support ticket so we can securely exchange the core dump that is generated in your system.

One final comment. I read xdebug 2.9.6 in the issue. Is it always this been the version even at the begin? I am asking because we know of problems with 2.9.4 and 2.9.5.

**Comment by alecavallo** [comment] 2020-09-10 12:58
Hi @labbati  . Initially, it has installed Xdebug v2.8.1. Then I updated it to v. 2.9.6 (thinking it was an issue caused by an old version of Xdebug).
Also, I tried removing Xdebug completely with no luck.

**Comment by labbati** [comment] 2020-09-10 13:05
Based on the last line in the xdebug output is seems to be related to Redis.
If you are able to recreate the issue in a dev/testing environment, would it be possible to try with `DD_TRACE_PHPREDIS_ENABLED=false` to see if the segfault goes away?

It might be a coincidence, but worth ruling out if it is not too much trouble

**Comment by alecavallo** [comment] 2020-09-10 13:18
@labbati Thanks!! After setting the variable you specified, the issue is not reproducible.
What doest that change do? I can't find that variable in the documentation.
Thanks!

**Comment by labbati** [comment] 2020-09-10 13:28
In the [docs}(https://docs.datadoghq.com/tracing/setup/php/#environment-variable-configuration) you can find it searching for `DD_TRACE_<INTEGRATION>_ENABLED`.

What the variable does is disabling the phpredis integration. I was not able to reproduce yet. I will let you know as soon as I have news.

**Comment by labbati** [comment] 2020-09-10 16:16
Hi @alecavallo. While we have not yet been able to reproduce this issue, we believe that it is related to #1013 as the underlying cause.

If you were able to generate the segfault in a non production environment, would you mind to validate that our assumption is correct testing this custom build? In order to do this you'd need to:

1. Install this apk package instead of 0.48.1: https://222584-119990860-gh.circle-artifacts.com/0/datadog-php-tracer_1.0.0-nightly_noarch.apk
2. remove the setting `DD_TRACE_PHPREDIS_ENABLED=false` that you had set before.

We are still trying to recreate to be 100% sure, though.

**Comment by labbati** [comment] 2020-09-10 16:38
@alecavallo I wanted to provide an update before I have to sign-off.

1. I setup locally an app using your `Dockerfile` and a sample CakePHP 2.10.19 app using Redis.
2. I put it under siege with thousand of requests
3. I had no luck recreating your segfault

Here is how I suggest to proceed, if you are available:

1. Based on the xdebug output, we are still confident that the issue is the one solved on #1013. In order to validate this I'd ask you, whenever have time, to do [what I suggested in my previous comment](https://github.com/DataDog/dd-trace-php/issues/1012#issuecomment-690429889)
2. On top of that, if you could provided with the generated core dump, we can better look into it and confirm.

Thank you again for the detailed info that you provided that allowed us to recreate a similar environment in a very short amount of time.

If you have any further questions please mention @morrisonlevi. I will followup again tomorrow on this.

**Comment by alecavallo** [comment] 2020-09-10 18:58
@labbati The new version fixes the issue. I couldn't reproduce the error.
Thanks!

**Comment by SammyK** [comment] 2020-09-10 20:49
@alecavallo Thank you for confirming that the custom build fixed the issue for you. The patch for this issue has been [released in `0.48.2`](https://github.com/DataDog/dd-trace-php/releases/tag/0.48.2). Please feel free to reach out if you're still having any more problems with this and thank you again for the report!

**Closed** 2020-09-10 21:04 UTC
Labels: 🐛 bug
