### ISSUE TITLE
[BUG] Symfony integration is not working on 0.71.0

### ISSUE THREAD

**Issue by blazarecki** [DataDog/dd-trace-php#1549] opened 2022-03-29 12:55 UTC
### Bug description

Hi, Since I update the extension from 0.69.0 to 0.71.0 I lose the Symfony integration. 
I'm not sure this is due to the extension or something else. 

- Now on the APM only the `web.request` operation is available, the `symfony.request` disappear. 
- On a trace I do not see the `symfony.request` span anymore but the `web.request` one. 
- On a trace the `symfony` tag disappear. 

Here an exemple of before:

![Capture d’écran 2022-03-29 à 12 01 23](https://user-images.githubusercontent.com/1443312/160613921-85664013-32cf-40e1-8e24-320b3fd09536.png) 

Using the DD_TRACE_DEBUG="true" here the output of the log

![Capture d’écran 2022-03-29 à 12 00 38](https://user-images.githubusercontent.com/1443312/160613820-42a81167-d70c-47db-99f7-6bd9e3470691.png)

As you can see the Symfony integration is loaded. 

### PHP version
```
PHP 8.1.4 (cli) (built: Mar 29 2022 02:04:55) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.4, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.4, Copyright (c), by Zend Technologies
    with ddtrace v0.71.0, Copyright Datadog, by Datadog
```

### Tracer version
```
0.71.0
```

### Installed extensions
```
[PHP Modules]
apcu
Core
ctype
curl
date
ddtrace
dom
fileinfo
filter
ftp
hash
iconv
intl
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
ddtrace
```

### OS info
```
NAME="Alpine Linux"
VERSION_ID=3.15.3
PRETTY_NAME="Alpine Linux v3.15"
```

Currently running on AWS ECS Fargate.

### Upgrading info

Previous install extension: 0.69.0 on a docker image base on alpine.
New version: 0.71.0 on a docker image base on alpine.

Thanks.

**Comment by bwoebi** [comment] 2022-03-29 12:57
Hey,

thanks for the report, at a first glance, this looks similar to #1544.
Can you confirm whether that's the indeed same issue?

Thanks!

**Comment by annuh** [comment] 2022-03-29 14:24
We noticed the same issue. We 'fixed' it by downgrading to PHP 8.1.3.

**Comment by bwoebi** [comment] 2022-03-29 14:41
@annuh thanks for that pointer, we're going to investigate, our testing environment is not using 8.1.4 yet - we're going to try this.

**Comment by blazarecki** [comment] 2022-03-29 15:46
It's working like a charm on PHP 8.1.3.
Thanks for the quick reply @bwoebi and @annuh.

**Comment by bwoebi** [comment] 2022-03-29 16:15
We have identified the cause for this issue. It will be fixed in the next patch release.

It's caused by a subtle change in PHP 8.1.4.

**Comment by blazarecki** [comment] 2022-03-29 16:27
Thanks.

**Closed** 2022-03-29 16:55 UTC
Labels: 🐛 bug

**Comment by blazarecki** [comment] 2022-04-04 11:48
Thanks
