### ISSUE TITLE
dd-trace-php 0.36.0 to 0.37.1 conflicts with newrelic

### ISSUE THREAD

**Issue by dcsg** [DataDog/dd-trace-php#726] opened 2020-01-20 18:06 UTC
After upgrading dd-trace-php from 0.35.0 to 0.37.1 we started having this error:
`[php7:notice] [pid 19232] [client 10.10.101.76:63396] Found blacklisted module: newrelic, disabling conflicting functionality`

We had to rollback this update. Anything we should do?

**Comment by dcsg** [comment] 2020-01-20 21:19
I've tested and any version after 0.35.0 gives that same error

**Comment by labbati** [comment] 2020-01-21 10:00
Hi @dcsg, we recently added this safety net. We observed that when we work together with a restricted set of other libraries, potential memory issues/segfault may arise that are not predictable by us. Those libraries are some the ones that do something very similar to what we do, like in your example. Let me make it clear that is not the other library's fault.

We have a short-term and long-term plan to resolve this.

1. _short-term_: we are disabling our tracer if we detect any possible conflict and incompatibility. We print an error message to make it clear what was the cause. This way, e.g. if you want to test Datadog alongside any other tool you can install Datadog only on one server and keep the other libraries into the other servers.
2. _long-term_: we are changing the way we hook into the VM so we can work together with other similar libraries. Please note that this is not 'sometime in the future', this part of the plan is already happening, but it requires a little bit of time as changes are more deep. I cannot provide an ETA at the moment, other than 'we have developers currently working full time on it'.

Thanks for your patience.

**Comment by dcsg** [comment] 2020-01-21 22:16
Hi @labbati. Thanks for your reply. I didn't went deep to see the error but I was having 500 when I upgraded it in staging. And that change was introduced in 0.36.0 onwards, right? In that case to be able to upgrade the datadog php tracer it will force me to uninstall new relic?

**Comment by labbati** [comment] 2020-01-24 13:38
That is correct, at the moment they cannot work together. Again our   goal  is to  support this use  case  and  we   are  actively working on  it.

**Comment by mikesherov** [comment] 2020-04-02 18:30
HI @labbati thanks for the updates and work on this issue so far. My team just encountered this issue because we needed to update dd-trace-php for php7.4 and also use NewRelic. So, in this case, it kind of means we can't use dd-trace-php until it's resolved.

I know timelines are hard to predict, but do you have any new clarity on timing here since Jan 24th?

**Comment by labbati** [comment] 2020-04-08 09:00
Hi,  we are currently working on a major refactoring of our core engine to be able to work seamlessly with other extensions that play a role similar to our. Not an ETA, but dedicated resources are focusing on this.

**Comment by labbati** [comment] 2020-05-13 09:05
Hello I just wanted to provide an update on this. Finally the big refactoring that was required for this to be possible has been completed (thanks to our master @SammyK). We are currently working heavily testing it to make sure we can safely whitelist this module. We plan to release this by EOM on php 7. It might take a few more weeks on php 5.6 and will provide a new ETA for that.

**Comment by SammyK** [comment] 2020-06-03 19:17
Hello @dcsg and @mikesherov! We just [released 0.46.0](https://github.com/DataDog/dd-trace-php/releases) which addresses this issue on PHP 7. I'm going to close this issue but feel free to reopen if you have any trouble with the latest version.

**Closed by SammyK** 2020-06-03 19:17 UTC
