### ISSUE TITLE
[BUG] Odd behavior in forked CLI processes

### ISSUE THREAD

**Issue by mucha55** [DataDog/dd-trace-php#1158] opened 2021-02-25 17:48 UTC
### Bug description
Hello, we are experiencing some odd behavior in CLI processes that use `pcntl_fork()` with the `ddtrace` extension installed. This is in an environment where tracing is enabled for HTTP (PHP-FPM), but disabled for CLI ([due to an issue submitted by my colleague](https://github.com/DataDog/dd-trace-php/issues/1101)). Top-level processes behave well, but any forked processes take a consistent 5 seconds to exit after executing their code ([barebones example found here](https://gist.github.com/mucha55/3cd73d3258e5e9b175c2436fbedeaec7)). Tweaking the configuration (with full re-deployments in between) or manually flushing/finishing/closing spans and scopes has no effect on that delay; the only way to get forked processes to behave is by fully disabling (`ddtrace.disable=On`) or uninstalling the extension (`dpkg -r datadog-php-tracer`). Is there any way for us to remove this exit delay from forked CLI processes without affecting HTTP tracing?

### PHP version
```
PHP 7.4.11 (cli) (built: Oct  1 2020 19:44:09) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies
    with ddtrace v0.51.0, Copyright Datadog, by Datadog
```

### Installed extensions
```
[PHP Modules]
bcmath
Core
ctype
curl
date
ddtrace
dom
fileinfo
filter
ftp
gd
hash
iconv
imap
json
libxml
mbstring
memcached
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib
zookeeper

[Zend Modules]
Zend OPcache
ddtrace
```

### OS info
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
```

#### Output of phpinfo() (ddtrace >= 0.47.0)
```
ddtrace


Datadog PHP tracer extension
For help, check out the documentation at https://docs.datadoghq.com/tracing/languages/php/
(c) Datadog 2020

Datadog tracing support => enabled
Version => 0.51.0
DATADOG TRACER CONFIGURATION => {"date":"2021-02-22T20:27:03Z","os_name":"Linux datadog-example 5.4.0-1029-aws #30~18.04.1-Ubuntu SMP Tue Oct 20 11:09:25 UTC 2020 x86_64","os_version":"5.4.0-1029-aws","version":"0.51.0","lang":"php","lang_version":"7.4.2","env":"prod","enabled":true,"service":"datadog-example","enabled_cli":false,"agent_url":"http://10.128.1.236:8126","debug":false,"analytics_enabled":false,"sample_rate":1.000000,"sampling_rules":null,"tags":null,"service_mapping":null,"distributed_tracing_enabled":true,"priority_sampling_enabled":true,"dd_version":null,"architecture":"x86_64","sapi":"cli","ddtrace.request_init_hook":"/opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php","open_basedir_configured":false,"uri_fragment_regex":null,"uri_mapping_incoming":null,"uri_mapping_outgoing":null,"auto_flush_enabled":false,"generate_root_span":true,"http_client_split_by_domain":false,"measure_compile_time":true,"report_hostname_on_root_span":false,"traced_internal_functions":null,"auto_prepend_file_configured":false,"integrations_disabled":null,"enabled_from_env":true,"opcache.file_cache":null}

                               Diagnostics
Diagnostic checks => passed

Directive => Local Value => Master Value
ddtrace.disable => Off => Off
ddtrace.request_init_hook => /opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php => /opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php
```

**Comment by labbati** [comment] 2021-02-26 13:22
Hi @mucha55. Thank you for submitting this issue and for the excellent explanation.
I was able to reproduce the issue.

As a short-term mitigation:
1. set on your host machine `DD_TRACE_SHUTDOWN_TIMEOUT=0` (default value is 5000 ms)
2. in your php-fpm pool reset it to 5000, in `www.conf` set `env[DD_TRACE_SHUTDOWN_TIMEOUT] = 5000`.

Let we get back to you with a long term remediation.

It is clear that not tracing CLI sapi (as you have not set `DD_TRACE_CLI_ENABLED=true`) and having our background sender thread holding the script from exiting is a bug on our side.

**Comment by mucha55** [comment] 2021-02-26 16:29
Thank you for the speedy and thorough response!

Out of curiosity, is that environment variable documented anywhere? I didn't come across it when looking around ([mainly here](https://docs.datadoghq.com/tracing/setup_overview/setup/php/?tab=containers#environment-variable-configuration))

**Comment by labbati** [comment] 2021-02-26 17:12
Hi @mucha55 it is not documented and theoretically not required. We had only put it there for very particular (and handcrafted) use cases. Ideally, it will have to go have, eventually. Of course with no issues on the user's side.

**Comment by labbati** [comment] 2021-03-02 15:48
Hi @mucha55, let me circle back on this issue.

Work is in progress to improve our status of 'disabled'. This was the real issue. Work is in progress and I expect to be shipped early next week.

Note that this will not mean `pcntl` will work - although, work for https://github.com/DataDog/dd-trace-php/issues/1101 has been scheduled, too.

We were still registering services that impacted, in this case, threading and we should not when tracing is disabled.

**Comment by mucha55** [comment] 2021-03-02 15:54
I appreciate the update!

**Comment by labbati** [comment] 2021-06-15 19:23
I am closing this issue since the fix has been released and the actual support for pcntl will come later on.
Please comment in case you still observe any unexpected behaviors.

**Closed by labbati** 2021-06-15 19:23 UTC
Labels: cat:incompatibility, sev1, 🐛 bug
