### ISSUE TITLE
[BUG] Laravel Horizon queue APM on version > 0.87.0

### ISSUE THREAD

**Issue by s1rc** [DataDog/dd-trace-php#2080] opened 2023-05-26 14:30 UTC
### Bug description

- Previously we have been using this implementation with dd-trace version < `0.87.0` https://github.com/DataDog/dd-trace-php/issues/386#issuecomment-1487303134
- Upgraded dd-trace to `0.87.2` in a new docker image tag, we are only using APM
```
RUN curl -L -o /tmp/datadog-php-tracer_${DD_VER}_$(arch).apk https://github.com/DataDog/dd-trace-php/releases/download/${DD_VER}/datadog-php-tracer_${DD_VER}_$(arch).apk
RUN apk add /tmp/datadog-php-tracer_${DD_VER}_$(arch).apk --allow-untrusted
```
- Changed our k8s deployment to remove `DD_TRACE_GENERATE_ROOT_SPAN=0`, current ENV config:
```
worker-7677dd7954-47r92:/var/www# env | grep DD_
DD_TRACE_AGENT_URL=unix:///var/run/datadog/apm.socket
DD_TRACE_AUTO_FLUSH_ENABLED=1
DD_TRACE_CLI_ENABLED=1
DD_ENV=staging
DD_VERSION=develop-0e01e142
DD_ENTITY_ID=fc5246a2-7792-4a76-a4af-79a1993ef226
DD_TRACE_LARAVEL_ENABLED=1
DD_AGENT_HOST=10.0.31.12
DD_SERVICE=worker
```
- We will get a couple of APM traces show up within the service resources filtering by operation `laravel.queue.process`
- After a few minutes, new traces for that operation stop, other service operations are still being ingested

### PHP version

```
PHP 8.2.6 (cli) (built: May 11 2023 20:27:34) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.6, Copyright (c), by Zend Technologies
    with ddtrace v0.87.2, Copyright Datadog, by Datadog
```
### Tracer version

`0.87.2`

### Installed extensions

<details>
  <summary>Click me</summary>

```
[PHP Modules]
bcmath
bz2
Core
ctype
curl
date
ddtrace
dom
exif
fileinfo
filter
ftp
gd
hash
iconv
imagick
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
random
readline
Reflection
session
SimpleXML
sockets
sodium
  SPL
  sqlite3
  standard
  swoole
  tokenizer
  xml
  xmlreader
  xmlwriter
  Zend OPcache
  zip
  zlib
  
  [Zend Modules]
  Zend OPcache
  ddtrace
  ```
</details>

### OS info

```
NAME="Alpine Linux"
VERSION_ID=3.18.0
PRETTY_NAME="Alpine Linux v3.18"
```
#### Output of phpinfo() (ddtrace >= 0.47.0)

<details>
  <summary>Click me</summary>

```
ddtrace


Datadog PHP tracer extension
For help, check out the documentation at https://docs.datadoghq.com/tracing/languages/php/
(c) Datadog 2020

Datadog tracing support => enabled
Version => 0.87.2
DATADOG TRACER CONFIGURATION => {
    "date": "2023-05-26T14:15:11Z",
    "os_name": "Linux worker-7677dd7954-47r92 5.10.178-162.673.amzn2.aarch64 #1 SMP Mon Apr 24 23:34:12 UTC 2023 aarch64",
    "os_version": "5.10.178-162.673.amzn2.aarch64",
    "version": "0.87.2",
    "lang": "php",
    "lang_version": "8.2.1",
    "env": "staging",
    "enabled": true,
    "service": "worker",
    "enabled_cli": true,
    "agent_url": "unix:\/\/\/var\/run\/datadog\/apm.socket",
    "debug": false,
    "analytics_enabled": false,
    "sample_rate": 1,
    "sampling_rules": [],
    "tags": [],
    "service_mapping": [],
    "distributed_tracing_enabled": true,
    "priority_sampling_enabled": true,
    "dd_version": "develop-0e01e142",
    "architecture": "aarch64",
    "sapi": "cli",
    "datadog.trace.request_init_hook": "\/opt\/datadog-php\/dd-trace-sources\/bridge\/dd_wrap_autoloader.php",
    "open_basedir_configured": false,
    "uri_fragment_regex": null,
    "uri_mapping_incoming": null,
    "uri_mapping_outgoing": null,
    "auto_flush_enabled": true,
    "generate_root_span": true,
    "http_client_split_by_domain": false,
    "measure_compile_time": true,
    "report_hostname_on_root_span": false,
    "traced_internal_functions": null,
    "auto_prepend_file_configured": false,
    "integrations_disabled": "default",
    "enabled_from_env": true,
    "opcache.file_cache": null
}

                               Diagnostics                               
Diagnostic checks => passed

Directive => Local Value => Master Value
ddtrace.disable => Off => Off
ddtrace.cgroup_file => /proc/self/cgroup => /proc/self/cgroup
datadog.trace.request_init_hook => /opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php => /opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php
ddtrace.request_init_hook => /opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php => /opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php
datadog.trace.agent_url => unix:///var/run/datadog/apm.socket => unix:///var/run/datadog/apm.socket
datadog.agent_host => 10.0.31.12 => 10.0.31.12
datadog.dogstatsd_url => no value => no value
datadog.distributed_tracing => On => On
datadog.dogstatsd_port => 8125 => 8125
datadog.env => staging => staging
datadog.autofinish_spans => Off => Off
datadog.trace.url_as_resource_names_enabled => On => On
datadog.integrations_disabled => default => default
datadog.priority_sampling => On => On
datadog.service => worker => worker
datadog.service_name => worker => worker
datadog.service_mapping => no value => no value
datadog.tags => no value => no value
datadog.trace.global_tags => no value => no value
datadog.trace.agent_port => 0 => 0
datadog.trace.analytics_enabled => Off => Off
datadog.trace.auto_flush_enabled => On => On
datadog.trace.cli_enabled => On => On
datadog.trace.measure_compile_time => On => On
datadog.trace.debug => Off => Off
datadog.trace.enabled => On => On
datadog.trace.health_metrics_enabled => Off => Off
datadog.trace.health_metrics_heartbeat_sample_rate => 0.001 => 0.001
datadog.trace.db_client_split_by_instance => Off => Off
datadog.trace.http_client_split_by_domain => Off => Off
datadog.trace.redis_client_split_by_host => Off => Off
datadog.trace.memory_limit => no value => no value
datadog.trace.report_hostname => Off => Off
datadog.trace.flush_collect_cycles => Off => Off
datadog.trace.resource_uri_fragment_regex => no value => no value
datadog.trace.resource_uri_mapping_incoming => no value => no value
datadog.trace.resource_uri_mapping_outgoing => no value => no value
datadog.trace.resource_uri_query_param_allowed => no value => no value
datadog.trace.http_url_query_param_allowed => * => *
datadog.trace.http_post_data_param_allowed => no value => no value
datadog.trace.rate_limit => 0 => 0
datadog.trace.sample_rate => 1 => 1
datadog.sampling_rate => 1 => 1
datadog.trace.sampling_rules => [] => []
datadog.span_sampling_rules => [] => []
datadog.span_sampling_rules_file => no value => no value
datadog.trace.header_tags => no value => no value
datadog.trace.x_datadog_tags_max_length => 512 => 512
datadog.trace.propagate_service => Off => Off
datadog.trace.propagation_style_extract => tracecontext,Datadog,B3,B3 single header => tracecontext,Datadog,B3,B3 single header
datadog.propagation_style_extract => tracecontext,Datadog,B3,B3 single header => tracecontext,Datadog,B3,B3 single header
datadog.trace.propagation_style_inject => tracecontext,Datadog => tracecontext,Datadog
datadog.propagation_style_inject => tracecontext,Datadog => tracecontext,Datadog
datadog.trace.propagation_style => tracecontext,Datadog => tracecontext,Datadog
datadog.trace.traced_internal_functions => no value => no value
datadog.trace.agent_timeout => 500 => 500
datadog.trace.agent_connect_timeout => 100 => 100
datadog.trace.debug_prng_seed => -1 => -1
datadog.log_backtrace => Off => Off
datadog.trace.generate_root_span => On => On
datadog.trace.spans_limit => 1000 => 1000
datadog.trace.128_bit_traceid_generation_enabled => Off => Off
datadog.trace.agent_max_consecutive_failures => 3 => 3
datadog.trace.agent_attempt_retry_time_msec => 5000 => 5000
datadog.trace.bgs_connect_timeout => 2000 => 2000
datadog.trace.bgs_timeout => 5000 => 5000
datadog.trace.agent_flush_interval => 5000 => 5000
datadog.trace.agent_flush_after_n_requests => 10 => 10
datadog.trace.shutdown_timeout => 5000 => 5000
datadog.trace.startup_logs => On => On
datadog.trace.agent_debug_verbose_curl => Off => Off
datadog.trace.debug_curl_output => Off => Off
datadog.trace.beta_high_memory_pressure_percent => 80 => 80
datadog.trace.warn_legacy_dd_trace => On => On
datadog.trace.retain_thread_capabilities => Off => Off
datadog.version => develop-0e01e142 => develop-0e01e142
datadog.trace.obfuscation_query_string_regexp => (?i)(?:p(?:ass)?w(?:or)?d|pass(?:_?phrase)?|secret|(?:api_?|private_?|public_?|access_?|secret_?)key(?:_?id)?|token|consumer_?(?:id|key|secret)|sign(?:ed|ature)?|auth(?:entication|orization)?)(?:(?:\s|%20)*(?:=|%3D)[^&]+|(?:"|%22)(?:\s|%20)*(?::|%3A)(?:\s|%20)*(?:"|%22)(?:%2[^2]|%[^2]|[^"%])+(?:"|%22))|bearer(?:\s|%20)+[a-z0-9\._\-]|token(?::|%3A)[a-z0-9]{13}|gh[opsu]_[0-9a-zA-Z]{36}|ey[I-L](?:[\w=-]|%3D)+\.ey[I-L](?:[\w=-]|%3D)+(?:\.(?:[\w.+\/=-]|%3D|%2F|%2B)+)?|[\-]{5}BEGIN(?:[a-z\s]|%20)+PRIVATE(?:\s|%20)KEY[\-]{5}[^\-]+[\-]{5}END(?:[a-z\s]|%20)+PRIVATE(?:\s|%20)KEY|ssh-rsa(?:\s|%20)*(?:[a-z0-9\/\.+]|%2F|%5C|%2B){100,} => (?i)(?:p(?:ass)?w(?:or)?d|pass(?:_?phrase)?|secret|(?:api_?|private_?|public_?|access_?|secret_?)key(?:_?id)?|token|consumer_?(?:id|key|secret)|sign(?:ed|ature)?|auth(?:entication|orization)?)(?:(?:\s|%20)*(?:=|%3D)[^&]+|(?:"|%22)(?:\s|%20)*(?::|%3A)(?:\s|%20)*(?:"|%22)(?:%2[^2]|%[^2]|[^"%])+(?:"|%22))|bearer(?:\s|%20)+[a-z0-9\._\-]|token(?::|%3A)[a-z0-9]{13}|gh[opsu]_[0-9a-zA-Z]{36}|ey[I-L](?:[\w=-]|%3D)+\.ey[I-L](?:[\w=-]|%3D)+(?:\.(?:[\w.+\/=-]|%3D|%2F|%2B)+)?|[\-]{5}BEGIN(?:[a-z\s]|%20)+PRIVATE(?:\s|%20)KEY[\-]{5}[^\-]+[\-]{5}END(?:[a-z\s]|%20)+PRIVATE(?:\s|%20)KEY|ssh-rsa(?:\s|%20)*(?:[a-z0-9\/\.+]|%2F|%5C|%2B){100,}
datadog.trace.client_ip_enabled => Off => Off
datadog.trace.client_ip_header => no value => no value
datadog.trace.forked_process => On => On
datadog.trace.hook_limit => 100 => 100
datadog.trace.agent_max_payload_size => 52428800 => 52428800
datadog.trace.agent_stack_initial_size => 131072 => 131072
datadog.trace.agent_stack_backlog => 12 => 12
datadog.trace.propagate_user_id_default => Off => Off
datadog.dbm_propagation_mode => disabled => disabled
datadog.trace.amqp_enabled => On => On
datadog.trace.amqp_analytics_enabled => Off => Off
datadog.amqp_analytics_enabled => Off => Off
datadog.trace.amqp_analytics_sample_rate => 1 => 1
datadog.amqp_analytics_sample_rate => 1 => 1
datadog.trace.cakephp_enabled => On => On
datadog.trace.cakephp_analytics_enabled => Off => Off
datadog.cakephp_analytics_enabled => Off => Off
datadog.trace.cakephp_analytics_sample_rate => 1 => 1
datadog.cakephp_analytics_sample_rate => 1 => 1
datadog.trace.codeigniter_enabled => On => On
datadog.trace.codeigniter_analytics_enabled => Off => Off
datadog.codeigniter_analytics_enabled => Off => Off
datadog.trace.codeigniter_analytics_sample_rate => 1 => 1
datadog.codeigniter_analytics_sample_rate => 1 => 1
datadog.trace.curl_enabled => On => On
datadog.trace.curl_analytics_enabled => Off => Off
datadog.curl_analytics_enabled => Off => Off
datadog.trace.curl_analytics_sample_rate => 1 => 1
datadog.curl_analytics_sample_rate => 1 => 1
datadog.trace.elasticsearch_enabled => On => On
datadog.trace.elasticsearch_analytics_enabled => Off => Off
datadog.elasticsearch_analytics_enabled => Off => Off
datadog.trace.elasticsearch_analytics_sample_rate => 1 => 1
datadog.elasticsearch_analytics_sample_rate => 1 => 1
datadog.trace.eloquent_enabled => On => On
datadog.trace.eloquent_analytics_enabled => Off => Off
datadog.eloquent_analytics_enabled => Off => Off
datadog.trace.eloquent_analytics_sample_rate => 1 => 1
datadog.eloquent_analytics_sample_rate => 1 => 1
datadog.trace.guzzle_enabled => On => On
datadog.trace.guzzle_analytics_enabled => Off => Off
datadog.guzzle_analytics_enabled => Off => Off
datadog.trace.guzzle_analytics_sample_rate => 1 => 1
datadog.guzzle_analytics_sample_rate => 1 => 1
datadog.trace.laminas_enabled => On => On
datadog.trace.laminas_analytics_enabled => Off => Off
datadog.laminas_analytics_enabled => Off => Off
datadog.trace.laminas_analytics_sample_rate => 1 => 1
datadog.laminas_analytics_sample_rate => 1 => 1
datadog.trace.laravel_enabled => On => On
datadog.trace.laravel_analytics_enabled => Off => Off
datadog.laravel_analytics_enabled => Off => Off
datadog.trace.laravel_analytics_sample_rate => 1 => 1
datadog.laravel_analytics_sample_rate => 1 => 1
datadog.trace.laravelqueue_enabled => On => On
datadog.trace.laravelqueue_analytics_enabled => Off => Off
datadog.laravelqueue_analytics_enabled => Off => Off
datadog.trace.laravelqueue_analytics_sample_rate => 1 => 1
datadog.laravelqueue_analytics_sample_rate => 1 => 1
datadog.trace.lumen_enabled => On => On
datadog.trace.lumen_analytics_enabled => Off => Off
datadog.lumen_analytics_enabled => Off => Off
datadog.trace.lumen_analytics_sample_rate => 1 => 1
datadog.lumen_analytics_sample_rate => 1 => 1
datadog.trace.memcache_enabled => On => On
datadog.trace.memcache_analytics_enabled => Off => Off
datadog.memcache_analytics_enabled => Off => Off
datadog.trace.memcache_analytics_sample_rate => 1 => 1
datadog.memcache_analytics_sample_rate => 1 => 1
datadog.trace.memcached_enabled => On => On
datadog.trace.memcached_analytics_enabled => Off => Off
datadog.memcached_analytics_enabled => Off => Off
datadog.trace.memcached_analytics_sample_rate => 1 => 1
datadog.memcached_analytics_sample_rate => 1 => 1
datadog.trace.mongo_enabled => On => On
datadog.trace.mongo_analytics_enabled => Off => Off
datadog.mongo_analytics_enabled => Off => Off
datadog.trace.mongo_analytics_sample_rate => 1 => 1
datadog.mongo_analytics_sample_rate => 1 => 1
datadog.trace.mongodb_enabled => On => On
datadog.trace.mongodb_analytics_enabled => Off => Off
datadog.mongodb_analytics_enabled => Off => Off
datadog.trace.mongodb_analytics_sample_rate => 1 => 1
datadog.mongodb_analytics_sample_rate => 1 => 1
datadog.trace.mysqli_enabled => On => On
datadog.trace.mysqli_analytics_enabled => Off => Off
datadog.mysqli_analytics_enabled => Off => Off
datadog.trace.mysqli_analytics_sample_rate => 1 => 1
datadog.mysqli_analytics_sample_rate => 1 => 1
datadog.trace.nette_enabled => On => On
datadog.trace.nette_analytics_enabled => Off => Off
datadog.nette_analytics_enabled => Off => Off
datadog.trace.nette_analytics_sample_rate => 1 => 1
datadog.nette_analytics_sample_rate => 1 => 1
datadog.trace.pcntl_enabled => On => On
datadog.trace.pcntl_analytics_enabled => Off => Off
datadog.pcntl_analytics_enabled => Off => Off
datadog.trace.pcntl_analytics_sample_rate => 1 => 1
datadog.pcntl_analytics_sample_rate => 1 => 1
datadog.trace.pdo_enabled => On => On
datadog.trace.pdo_analytics_enabled => Off => Off
datadog.pdo_analytics_enabled => Off => Off
datadog.trace.pdo_analytics_sample_rate => 1 => 1
datadog.pdo_analytics_sample_rate => 1 => 1
datadog.trace.phpredis_enabled => On => On
datadog.trace.phpredis_analytics_enabled => Off => Off
datadog.phpredis_analytics_enabled => Off => Off
datadog.trace.phpredis_analytics_sample_rate => 1 => 1
datadog.phpredis_analytics_sample_rate => 1 => 1
datadog.trace.predis_enabled => On => On
datadog.trace.predis_analytics_enabled => Off => Off
datadog.predis_analytics_enabled => Off => Off
datadog.trace.predis_analytics_sample_rate => 1 => 1
datadog.predis_analytics_sample_rate => 1 => 1
datadog.trace.psr18_enabled => On => On
datadog.trace.psr18_analytics_enabled => Off => Off
datadog.psr18_analytics_enabled => Off => Off
datadog.trace.psr18_analytics_sample_rate => 1 => 1
datadog.psr18_analytics_sample_rate => 1 => 1
datadog.trace.roadrunner_enabled => On => On
datadog.trace.roadrunner_analytics_enabled => Off => Off
datadog.roadrunner_analytics_enabled => Off => Off
datadog.trace.roadrunner_analytics_sample_rate => 1 => 1
datadog.roadrunner_analytics_sample_rate => 1 => 1
datadog.trace.sqlsrv_enabled => On => On
datadog.trace.sqlsrv_analytics_enabled => Off => Off
datadog.sqlsrv_analytics_enabled => Off => Off
datadog.trace.sqlsrv_analytics_sample_rate => 1 => 1
datadog.sqlsrv_analytics_sample_rate => 1 => 1
datadog.trace.slim_enabled => On => On
datadog.trace.slim_analytics_enabled => Off => Off
datadog.slim_analytics_enabled => Off => Off
datadog.trace.slim_analytics_sample_rate => 1 => 1
datadog.slim_analytics_sample_rate => 1 => 1
datadog.trace.symfony_enabled => On => On
datadog.trace.symfony_analytics_enabled => Off => Off
datadog.symfony_analytics_enabled => Off => Off
datadog.trace.symfony_analytics_sample_rate => 1 => 1
datadog.symfony_analytics_sample_rate => 1 => 1
datadog.trace.web_enabled => On => On
datadog.trace.web_analytics_enabled => Off => Off
datadog.web_analytics_enabled => Off => Off
datadog.trace.web_analytics_sample_rate => 1 => 1
datadog.web_analytics_sample_rate => 1 => 1
datadog.trace.wordpress_enabled => On => On
datadog.trace.wordpress_analytics_enabled => Off => Off
datadog.wordpress_analytics_enabled => Off => Off
datadog.trace.wordpress_analytics_sample_rate => 1 => 1
datadog.wordpress_analytics_sample_rate => 1 => 1
datadog.trace.yii_enabled => On => On
datadog.trace.yii_analytics_enabled => Off => Off
datadog.yii_analytics_enabled => Off => Off
datadog.trace.yii_analytics_sample_rate => 1 => 1
datadog.yii_analytics_sample_rate => 1 => 1
datadog.trace.zendframework_enabled => On => On
datadog.trace.zendframework_analytics_enabled => Off => Off
datadog.zendframework_analytics_enabled => Off => Off
datadog.trace.zendframework_analytics_sample_rate => 1 => 1
datadog.zendframework_analytics_sample_rate => 1 => 1
```
</details>

### Upgrading info

Previous version `0.86.3`

**Comment by PROFeNoM** [comment] 2023-05-26 15:00
Thanks @s1rc :+1: I'm actively trying to debug this. By any chance (which could help me speed up the reproduction process), do you see any crash happening using DD_TRACE_DEBUG?

**Comment by s1rc** [comment] 2023-05-26 17:32
I have enabled `DD_TRACE_DEBUG` on the deployment. After the pods loaded I ran some jobs through the queue and they showed up in APM, logs below:

```
2023-05-26 17:21:48 App\Jobs\Access\RefreshOktaToken ............... RUNNING
2023-05-26 17:21:48 App\Jobs\Access\RefreshOktaToken ......... 187.58ms DONE
[2023-05-26T17:21:48+00:00] [ddtrace] [debug] - Loaded integration DDTrace\Integrations\PDO\PDOIntegration
Flushing trace of size 83 to send-queue for unix:///var/run/datadog/apm.socket
```

After a few minutes I saw this in the container logs, then no more traces were showing up under the service + env in APM.
```
[2023-05-26T17:22:38+00:00] [ddtrace] [debug] - Loaded integration DDTrace\Integrations\PDO\PDOIntegration
[2023-05-26T17:22:38+00:00] [ddtrace] [error] - Invalid value returning by integration loader for DDTrace\Integrations\Psr18\Psr18Integration: 
```

**Comment by s1rc** [comment] 2023-05-26 17:33
This has also shown up for a job we expected to error:

```
Error thrown in ddtrace's closure defined at /opt/datadog-php/dd-trace-sources/bridge/_generated_integrations.php:4041 for App\Exceptions\Handler::report(): Call to undefined method Exception::getStatusCode()
```

**Comment by morrisonlevi** [comment] 2023-05-26 23:42
Here's some context on the latter error about `getStatusCode`, which seems like a mistake on our end:

```php
4041         \DDTrace\hook_method('Illuminate\\Contracts\\Debug\\ExceptionHandler', 'report', function ($This, $scope, $     args) use($rootSpan, $integration) {
4042             if ($args[0] && $args[0]->getStatusCode() >= 500) {
4043                 $integration->setError($rootSpan, $args[0]);
4044             }   
4045         });
```

I can see from the definition of `ExceptionHandler::report` that this argument can be any `Throwable`, so usage of `getStatusCode()` is wrong in some cases (`Thowable::getStatusCode` doesn't exist). When searching online, I can find quite a few Laravel users calling `getStatusCode`. I haven't been able to track this down to any code which provides such a method _in Laravel_, though one exists for `Symfony\Component\HttpKernel\Exception::getStatusCode`. Laravel depends on `symfony/http-kernel` so maybe this is common.

@PROFeNoM I think we need to either guard that `getStatsCode` and similar with something like:

```php
            if (isset($args[0])
                && $args[0] instanceof \Symfony\Component\HttpKernel\Exception
                && $args[0]->getStatusCode() >= 500
            ) {
                $integration->setError($rootSpan, $args[0]);
            }
```

Or go back to the drawing board -- there may be a better Laravel-specific way to determine what to do here. As per @s1rc's report, not all exceptions going through this handler are `HttpException`s.

**Comment by PROFeNoM** [comment] 2023-05-30 08:29
There was indeed a mistake on the hook that was made on `ExceptionHandler::report` and this specific error should be fixed with #2062.

💭 On a side note, I tried running some jobs on a laravel app. More specifically, batches of jobs were scheduled to run every minutes to be processed by the worker processes spawned by Laravel Horizon, with some of these jobs throwing instances of `Exception`, which doesn't have the `getStatusCode` method. _Unfortunately_, it didn't prevent subsequent jobs from being traced, whether I was using the changes introduced with #2062 or not, or using your `QueueTraceServiceProvider` or the Laravel Queue Integration...

Could you please tell me @s1rc if this issue still happens on your app when using the `QueueTraceServiceProvider` you were using before, instead of the Laravel Queue integration? You can do so by setting `DD_TRACE_LARAVEL_ENABLED=0` and add the application service provider to your `config/app.php`. This would greatly help reducing the scope of the issue.

Thanks!

**Comment by s1rc** [comment] 2023-05-30 11:56
@PROFeNoM I will test this shortly. Do you want me to set up the same env config as well? 
```
DD_TRACE_CLI_ENABLED=1
DD_TRACE_AUTO_FLUSH_ENABLED=1
DD_TRACE_GENERATE_ROOT_SPAN=0
```
With the addition of:
```
DD_TRACE_LARAVEL_ENABLED=0
```

**Comment by PROFeNoM** [comment] 2023-05-30 15:37
Hey @s1rc,

This could indeed make sense to use `DD_TRACE_GENERATE_ROOT_SPAN=0` as this is what you were using previously, but since you seem to be using it set to `1` in your app now, the latter also have some valuable information 🤔 

Also, could you use this [datadog-setup.php artifact](https://output.circle-artifacts.com/output/job/5e92e8d9-fd7b-46a8-84d6-6ac8309276da/artifacts/0/datadog-setup.php)? It basically does two things: When you will be trying to use the Laravel queues integration _and_ `DD_TRACE_GENERATE_ROOT_SPAN=1`, new `laravel.queue.process` will be started (so that there are not under a `laravel.artisan` root span and visible in the app as they are happening in this configuration), and it also adds a debug log that says when the Span Limit has been hit.

When using this artifact:
- Is the issue still happening?
- If yes, is there a debug log `Span limit reached. Entering limited mode.` as the same time you start not seeing any new traces from Laravel queues?

Thanks a lot for your help.

PS: If you're not familiar with the process, to use the artifact, simply replace the link to the `datadog-setup.php` you were using in your Dockerfile to the one above :+1:

**Comment by s1rc** [comment] 2023-06-02 14:14
@PROFeNoM sure, I have send a DM on Slack.

**Closed** 2023-06-14 10:05 UTC
Labels: 🐛 bug
