### ISSUE TITLE
[BUG] - Repeated segfaults when datadog trace extension is installed with xdebug

### ISSUE THREAD

**Issue by soundsgoodsofar** [DataDog/dd-trace-php#771] opened 2020-02-26 21:55 UTC
**Describe the bug**
I've tested with both 0.40.0 and 0.39.2.  The same issue shows up on both.

Narrowed this down to the datadog trace package.  When I do not install it, everything works fine.  When I do install it, I php-fpm children segfault and die repeatedly.

Example log output with datadog installed:
php-fpm_1    | [26-Feb-2020 21:49:19] WARNING: [pool www] child 143 exited on signal 11 (SIGSEGV) after 15.002199 seconds from start
php-fpm_1    | [26-Feb-2020 21:49:19] NOTICE: [pool www] child 148 started
php-fpm_1    | [26-Feb-2020 21:49:22] WARNING: [pool www] child 144 exited on signal 11 (SIGSEGV) after 18.347624 seconds from start
php-fpm_1    | [26-Feb-2020 21:49:22] NOTICE: [pool www] child 149 started
php-fpm_1    | 192.168.160.6 -  26/Feb/2020:21:49:24 +0000 "GET /index.php" 200
php-fpm_1    | 192.168.160.6 -  26/Feb/2020:21:49:33 +0000 "GET /index.php" 200
php-fpm_1    | [26-Feb-2020 21:49:34] WARNING: [pool www] child 148 exited on signal 11 (SIGSEGV) after 14.996903 seconds from start
php-fpm_1    | [26-Feb-2020 21:49:34] NOTICE: [pool www] child 154 started
php-fpm_1    | [26-Feb-2020 21:49:34] WARNING: [pool www] child 149 exited on signal 11 (SIGSEGV) after 11.651510 seconds from start
php-fpm_1    | [26-Feb-2020 21:49:34] NOTICE: [pool www] child 155 started

Example log output when it is removed:
php-fpm_1    | 192.168.208.6 -  26/Feb/2020:21:50:23 +0000 "GET /index.php" 200
php-fpm_1    | 192.168.208.6 -  26/Feb/2020:21:50:24 +0000 "GET /index.php" 200
php-fpm_1    | 192.168.208.7 -  26/Feb/2020:21:50:28 +0000 "GET /php-fpm/status" 200
php-fpm_1    | 192.168.208.7 -  26/Feb/2020:21:50:28 +0000 "GET /php-fpm/ping" 200
php-fpm_1    | 192.168.208.6 -  26/Feb/2020:21:50:33 +0000 "GET /index.php" 200
php-fpm_1    | 192.168.208.6 -  26/Feb/2020:21:50:35 +0000 "GET /index.php" 200

**PHP Info**
- Output of `php -v`
\# php -v
PHP 7.3.13 (cli) (built: Dec 28 2019 21:22:54) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.9.2, Copyright (c) 2002-2020, by Derick Rethans

- Output of `php -m`
 \# php -m
[PHP Modules]
Core
ctype
curl
date
ddtrace
dom
fileinfo
filter
ftp
gd
hash
iconv
json
libxml
mbstring
mcrypt
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
sodium
SPL
sqlite3
standard
tokenizer
xdebug
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
Xdebug

**OS Info**
- Output of `cat /etc/os-release | grep -E "(NAME)|(VERSION)"`
\# cat /etc/os-release | grep -E "(NAME)|(VERSION)"
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

**Output of dd-doctor**
- PHP version and SAPI                               [7.3.13 - fpm-fcgi]
- ddtrace extension installed                        [OK]
- ddtrace version (installed)                        [0.39.2]
- ddtrace version (const)                            [0.39.2]
- ddtrace version (userland)                         [0.39.2]
- ddtrace versions in sync                           [OK]
- dd_trace() function available                      [OK]
- dd_trace_env_config() function available           [OK]
- ddtrace.request_init_hook set                      [OK]
- ddtrace.request_init_hook reachable                [OK]
- ddtrace.request_init_hook has run                  [OK]
- 'open_basedir' allows access to '/proc/self/'      [OK]
- IntegrationsLoader exists                          [OK]
- Integrations not loaded yet                        [OK]
- Registering an autoloader...
- Integrations loaded                                [OK]
- DDTrace\Tracer class exists                        [OK]
- Background sender is enabled?                      [NO]
  > You can enable the background sender via
    DD_TRACE_BETA_SEND_TRACES_VIA_THREAD=true
- Configured Agent host                              [datadog]
- Configured Agent port                              [8126]
- Agent can receive traces                           [OK]

**If you are upgrading**
n/a

**Comment by morrisonlevi** [comment] 2020-02-27 02:42
Thank you for the report, and sorry you are having problems. I have a few questions:
-  If you disable XDebug and keep ddtrace enabled, do you still have this issue?
- Do you have any idea why this is occurring 11-18 seconds after the fpm child is created?
- And lastly, do you have a core file? If so, can you send us a backtrace? If it contains anything sensitive please send it to support@datadoghq.com, but if not you can put it here.

**Comment by soundsgoodsofar** [comment] 2020-02-28 22:18
Hey @morrisonlevi , I disabled xdebug and the issue does appear to stop when I do that, so likely some kind of bad interaction with xdebug.

I have no idea why it's happening 11-18 seconds after the child starts, but that is definitely interesting.

I do not have a core dump, believe I'd need to recompile my kernel to enable that, and that would be a bit of work in this container for us at the moment.

**Comment by soundsgoodsofar** [comment] 2020-03-10 15:14
Well I tried to get a core dump but I'm having some problems.

When I compile php with enable-debug to attempt to get core dumps, it seems that the packaged installer of ddtrace won't work.  I get the following output.

        Selecting previously unselected package datadog-php-tracer.
    (Reading database ... 13026 files and directories currently installed.)
    Preparing to unpack datadog-php-tracer_0.40.0_amd64.deb ...
    Unpacking datadog-php-tracer (0.40.0) ...
    Setting up datadog-php-tracer (0.40.0) ...
    ### Installing Datadog PHP tracing extension (ddtrace)
    ###
    ### Logging /usr/local/bin/php -i to a file
    ###
    ### Creating ddtrace.ini
    ### 

    ; ***** DO NOT EDIT THIS FILE *****
    ; To overwrite the INI settings for this extension, edit
    ; the INI file in this directory called "ddtrace-custom.ini"

    [datadog]
    extension=/opt/datadog-php/extensions/ddtrace-20180731.so
    ddtrace.request_init_hook=/opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php
    ### ddtrace.ini created
    ###
    ### Created empty /opt/datadog-php/etc/ddtrace-custom.ini
    ###
    ### Linking ddtrace.ini for supported SAPI's
    ### 

    ### Found SAPI config directory: /usr/local/etc/php/conf.d
    ### Linking ddtrace.ini to /usr/local/etc/php/conf.d/98-ddtrace.ini
    ### Linking ddtrace-custom.ini to /usr/local/etc/php/conf.d/99-ddtrace-custom.ini
    ###
    PHP Warning:  PHP Startup: ddtrace: Unable to initialize module
    Module compiled with build ID=API20180731,NTS
    PHP    compiled with build ID=API20180731,NTS,debug
    These options need to match
     in Unknown on line 0
    ### Failed enabling ddtrace extension
    ###
    ### The extension has been installed but couldn't be enabled
    ### Try adding the extension manually to your PHP - php.ini - configuration file
    ### e.g. by adding following line: 
    ###
    ###     extension=/opt/datadog-php/extensions/ddtrace-20180731.so
    ###
    ### Note that your PHP API version must match the extension's API version
    ### PHP API version can be found using following command
    ###
    ###     /usr/local/bin/php -i | grep 'PHP API'
    ###

I tried to compile the ddtrace client from source ([following steps here](https://docs.datadoghq.com/tracing/faq/php-tracer-manual-installation/)).  When I do that, the segfaults stop, but so does the reporting.  I also don't see APM activity in our account, so clearly something isn't configured correctly, but I'm not sure what--everything else should be the same.  I did get it to the point where I saw the ddtrace module loaded up in php -i.

**Comment by labbati** [comment] 2020-03-11 11:20
You can replace `extension=/opt/datadog-php/extensions/ddtrace-20180731.so` with `extension=/opt/datadog-php/extensions/ddtrace-20180731-debug.so` in your ini file.

**Comment by SammyK** [comment] 2020-04-15 20:27
Hey @soundsgoodsofar! I'm glad to hear that disabling Xdebug fixed the issue. We've been working on making the tracer more compatible with Xdebug, but we recommend disabling Xdebug for now due to known conflicts.

I'm going to close this due to inactivity, but feel free to re-open if you're still having issues.

**Comment by soundsgoodsofar** [comment] 2020-04-17 16:45
@SammyK Sorry but I wouldn't say I'm "glad" about that at all.  I am still experiencing the issue, and I haven't had time to try getting my PHP compiled back with core dump support again.  It's complicated because that needs to happen three dockerfiles deep so I have to basically re-write the whole stack or fork the lowest container.

This is a a major issue for our development environment--we rely on xdebug, and we would still like to have a useable APM.  This may force us back to NewRelic.

**Comment by SammyK** [comment] 2020-04-17 17:04
@soundsgoodsofar I'm sorry to hear this is still an issue for you. I'll certainly re-open this so that we can keep the conversation active.

Our next release contains a big improvement with compatibility with neighboring extensions that hook opcodes. And the [latest version of Xdebug 2.9.4](https://xdebug.org/announcements/2020-03-23) contains an improvement for the same thing.

I'll ping you when the release is available which should be sometime next week. :)

Until then, what are your Xdebug INI settings?

**Comment by soundsgoodsofar** [comment] 2020-04-17 17:21
Thanks @SammyK , would be happy to try that as soon as it's available.  We pick up xdebug updates in our daily builds and it appears we're on 2.9.4 already.  I'm not sure I've tried the DD extension since that update so I can give it a shot as well.

Here is our xdebug.  The port gets configured by orchestration to connect to the correct developer instance.

> xdebug.remote_autostart=1
> xdebug.remote_enable=1
> xdebug.remote_connect_back=0
> xdebug.cli_color=0
> xdebug.profiler_enable=0
> xdebug.profiler_enable_trigger=0
> xdebug.profiler_output_dir=[REDACTED]
> xdebug.remote_handler=dbgp
> xdebug.remote_mode=req
> 
> xdebug.remote_port=${XDEBUG_PORT}
> xdebug.remote_host=172.17.0.1
> xdebug.idekey=PHPSTORM

**Comment by SammyK** [comment] 2020-04-17 17:29
@soundsgoodsofar Sounds good! Thanks for sharing the settings. I'll try to reproduce this on my end.

And I will ping you next week when the release is out. :)

**Comment by SammyK** [comment] 2020-04-17 19:15
Hey @soundsgoodsofar! I was able to reproduce this issue with `xdebug.remote_enable=1`. This is related to [an open issue in Xdebug](https://bugs.xdebug.org/view.php?id=1775). The fix has been merged into [Xdebug's master branch](https://github.com/xdebug/xdebug/commit/6c6c08233593ffc1d64d70c51c56f567e6528010) and I confirmed that the patch fixed the crash on my end. It looks like the fix is slated for the Xdebug 2.9.5 release.

I'll leave this issue open until Xdebug 2.9.5 is released so you can confirm that it fixes the issue on your end.

Thanks so much for reporting this issue and all the help tracking it down!

**Comment by SammyK** [comment] 2020-04-22 18:36
Hey @soundsgoodsofar! We just released `0.43.0` of the PHP tracer which contains significant improvements to working well with neighboring extensions. https://github.com/DataDog/dd-trace-php/releases/tag/0.43.0

Upgrading won't fix this particular issue since the issue is on the Xdebug side, but I still wanted to let you know since the release does contain a number of overall improvements.

I just checked the [Xdebug releases](https://xdebug.org/announcements) and the patch hasn't been released yet, but I'll keep any eye out for you. :)

**Comment by SammyK** [comment] 2020-04-27 15:30
@soundsgoodsofar I noticed that [Xdebug 2.9.5 was released](https://xdebug.org/announcements/2020-04-25) and can confirm it fixed the issue on my end. Would you mind confirming this issued is fixed on your end after upgrading Xdebug to 2.9.5?

**Comment by soundsgoodsofar** [comment] 2020-04-27 17:48
Thank you for the updates @SammyK !  I will work on getting everything updated and let you know if it's working.

**Comment by labbati** [comment] 2020-05-13 09:01
@soundsgoodsofar I am going ahead and closing this issue as we don't envision any more work on this after 0.45.0. Please feel free to re-open it if your use case hasn't been fixed yet and thanks for taking the time to open it.

**Closed by labbati** 2020-05-13 09:01 UTC
Labels: 🐛 bug
