### ISSUE TITLE
EventDispatcher Symfony 4.3 required completely fixing 

### ISSUE THREAD

**Issue by avelgsv** [DataDog/dd-trace-php#537] opened 2019-08-20 15:32 UTC
This fix (https://github.com/DataDog/dd-trace-php/pull/466) does not completely fixing issue.

This place (https://github.com/DataDog/dd-trace-php/pull/466/files#diff-4d8986aca121428d36d77e24776a0704R186) make Exception (Undefined offset: 1) then second argument of dispatch is empty.
Please, Add check in this place as same with `if (isset($args[1]) && is_string($args[1])) {` (line 145)

**Comment by labbati** [comment] 2019-08-20 15:57
Thanks for reporting this. We will add that check and look better into the code to make sure there are not other cases we miss.

Note that we are going to release in the next few days a rewrite of our internal calling mechanism that will NOT FAIL if errors like this happens. While this is not a fix (we have to address the real root cause of course) at least it will prevent your app to crash.

**Comment by kunicmarko20** [comment] 2019-09-04 10:50
Hey, @labbati did the release happen? I can't see any fix in https://github.com/DataDog/dd-trace-php/releases/tag/0.30.1, we didn't expect datadog to break our live environment if we update our project dependencies.

**Comment by labbati** [comment] 2019-09-04 11:03
Hi, this specific release is not happened yet. What we are doing is starting to roll them out. First will be:
- the new safety nets to happen this from happening in the future
- pdo migrated to the new api
- symfony (I will make sure this is added) migrated to the new api

Thanks for you patience.

**Comment by ben-challis** [comment] 2019-11-04 15:40
Hi @labbati, this issue is blocking an upgrade to Symfony 4.3, with 4.2 soon entering EOL. Is there any progress / upcoming work here? It looks a relatively trivial bug to patch in the interim before the rework you've mentioned above which appears to still have not taken place?

**Comment by labbati** [comment] 2019-11-05 11:04
Hi @avelgsv and @ben-challis, while we are still working to test Symfony 4.3, this specific issue was [fixed](https://github.com/DataDog/dd-trace-php/blame/1b052448bfbfd7346ec39e32bd6d28b716f22781/src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php#L187). Now this error will not happen anymore.

I will try my best to make some time during the week to test Symfony 4.3 to avoit adding further regressions.

In the meantime, if you have a dev environment with Symfony 4.3 installed and you can give it a spin it would be great. Thanks for the patience.

**Comment by labbati** [comment] 2019-11-11 12:49
Hi @ben-challis were you able to verify if this fix works for you? I made some tests in my testing app and this has been solved. Still planning too add tests for Symfony 4.3 though.

**Comment by ben-challis** [comment] 2019-11-11 13:55
Hi @labbati - currently in test with Symfony 4.3 & dd-trace containing the fix, initially all seems well :+1:.

**Comment by labbati** [comment] 2019-11-11 15:10
Thanks for the update @ben-challis!

**Comment by SammyK** [comment] 2020-04-15 21:39
Closing this issue as resolved. Please feel free to reopen if you're still having issues.

**Closed by SammyK** 2020-04-15 21:39 UTC
Labels: integrations, 🐛 bug
