### ISSUE TITLE
DDTrace/Configuration/EnvVariableRegistry.php tried to allocate 140119769395488 bytes

### ISSUE THREAD

**Issue by ctrlrsf** [DataDog/dd-trace-php#480] opened 2019-06-14 13:16 UTC
Just had outage caused by this issue. 24 of these errors were logged before Apache/PHP started returning 500s for all requests.

```
[php7:error] [pid 30949] [client 10.1.10.79:9456] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 140119769395488 bytes) in /opt/datadog-php/dd-trace-sources/src/DDTrace/Configuration/EnvVariableRegistry.php on line 95
```
`zend_mm_heap corrupted` was also logged during this time.

datadog-php-tracer version: 0.25.0
PHP version:
```
PHP 7.2.19-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:16:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by pawelchcki** [comment] 2019-06-21 12:19
Thank you for reporting this issue! Currently we're investigating the possible root cause

**Comment by labbati** [comment] 2019-11-12 20:11
@ctrlrsf revamping this issue after a while as  this  issue should have been gone  from a long time but I just wanted your  confirmation.

**Comment by albustax** [comment] 2019-12-03 13:25
Hi ! Same here. We get this error in production
```
Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 7234273483069944984 bytes) in /opt/datadog-php/dd-trace-sources/src/DDTrace/Transport/Http.php on line 140" while reading response header from upstream,
```
then all requests returned `500`

```
datadog-php-tracer                 0.30.1
php7.2-fpm                         7.2.24-1+0~20191026.31+debian9~1.gbpbbacde
```
```
PHP 7.2.24-1+0~20191026.31+debian9~1.gbpbbacde (cli) (built: Oct 26 2019 14:18:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-1+0~20191026.31+debian9~1.gbpbbacde, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by labbati** [comment] 2019-12-03 14:27
Hello! Would you please provide me the output of `php -m` to check with modules were enabled?
If you prefer to keep it confidential please open a support ticket to provide it.
Thank you.

**Comment by labbati** [comment] 2019-12-13 09:07
Hi @albustax, did you have a chance to execute the suggested command above `php -m` on the right version of php used by your server?

**Comment by labbati** [comment] 2019-12-13 09:08
@ctrlrsf this issue is pretty old, do you still experience this problem with the newest version of the tracer? Also if you could provide the output of `php -m` for the right version of php it could be very useful.

**Comment by albustax** [comment] 2019-12-13 09:28
Hi,

I opened a support ticket (#289474) with the output. Sorry for the delay.

**Comment by labbati** [comment] 2019-12-17 12:32
Thank you @albustax, support is reaching out to you with a suggestion. If this is confirmed then we can quickly provide a custom build for you to try out, if you are interested.

**Comment by SammyK** [comment] 2020-01-08 17:07
Hey @ctrlrsf and @albustax! The [latest release `0.37.0`](https://github.com/DataDog/dd-trace-php/releases) addresses an issue similar to this one. Would you mind confirming that this issue is resolved for you after [upgrading to the latest release](https://docs.datadoghq.com/tracing/setup/php/#upgrading)? :)

**Comment by labbati** [comment] 2020-01-17 16:08
Hi @ctrlrsf and @albustax I am closing this issue as we believe that the underlying bug is resolved.
Also, the support team should have asked you to do a final check to make sure. Feel free to re-open it in case the issue is still there.

**Closed by labbati** 2020-01-17 16:08 UTC
Labels: 🐛 bug
