### ISSUE TITLE
[Feature] Include max memory usage in root span

### ISSUE THREAD

**Issue by matthewnessworthy** [DataDog/dd-trace-php#2724] opened 2024-06-20 08:21 UTC
### Describe the feature you'd like

It would be great to get an overview of the most memory intensive operations, specifically for processes that have a bit less visibility, very specifically, Laravel queue jobs

### Is your feature request related to a problem?

Sometimes our DD dashboards indicate queue worker services hitting 100% memory usage, but because the service handles a plethora of queue jobs, tracking down the jobs that are causing memory issues is tricky at best

**Comment by realFlowControl** [comment] 2024-06-20 15:03
Hey there 👋
do you by chance use the profiler and the tracer, or just the tracer?
Kind regards
Florian

**Comment by matthewnessworthy** [comment] 2024-06-20 15:23
We do have the profiler setup, but i'm unaware of a way to group all queue actions, filter based on memory usage, and review the specific offending jobs

**Comment by realFlowControl** [comment] 2024-07-03 10:09
Hey @matthewnessworthy,
Sorry for the radio silence, I am back from conferences now!
I found you on the [Datadog Public Slack](https://chat.datadoghq.com/) and DM'ed you there.

**Comment by bwoebi** [comment] 2024-09-06 13:07
Closing this as a duplicate of #2832.

**Closed by bwoebi** 2024-09-06 13:07 UTC
Labels: feature-request
